<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="blockdiagram"
    nsURI="http://www.esmp.org/dsm/BlockDiagram/1.0.0" nsPrefix="blockdiagram">
  <eClassifiers xsi:type="ecore:EClass" name="BlockDiagram" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocks" ordered="false"
        upperBound="-1" eType="#//Block" containment="true" eOpposite="#//Block/blockDiagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connections" ordered="false"
        upperBound="-1" eType="#//Connection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="#//NamedElement #//ParameterableElement">
    <eOperations name="getInput" ordered="false" lowerBound="1" eType="#//Input">
      <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getOutput" ordered="false" lowerBound="1" eType="#//Output">
      <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputPorts" upperBound="-1"
        eType="#//InputPort" changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
        eType="#//Output" containment="true" eOpposite="#//Output/block"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
        eType="#//Input" containment="true" eOpposite="#//Input/block"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputPorts" upperBound="-1"
        eType="#//OutputPort" changeable="false" volatile="true" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1"
        eType="#//BlockType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="virtual" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blockDiagram" ordered="false"
        lowerBound="1" eType="#//BlockDiagram" eOpposite="#//BlockDiagram/blocks"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterableElement" abstract="true">
    <eOperations name="getParameter" ordered="false" lowerBound="1" eType="#//Parameter">
      <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getParameterValue" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//NamedElement">
    <eAnnotations source="duplicates">
      <contents xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false" volatile="true" transient="true" derived="true">
        <eAnnotations source="redefines" references="#//NamedElement/name"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="descriptor" ordered="false"
        lowerBound="1" eType="#//ParameterDescriptor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterDescriptor" abstract="true"
      eSuperTypes="#//NamedElement">
    <eAnnotations source="duplicates">
      <contents xsi:type="ecore:EAttribute" name="defaultValue" ordered="false" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false" volatile="true" transient="true" derived="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPort" eSuperTypes="#//Port">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingConnection" ordered="false"
        eType="#//Connection" eOpposite="#//Connection/targetPort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="directFeedthrough" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" ordered="false"
        lowerBound="1" eType="#//Input" eOpposite="#//Input/ports"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port" abstract="true" eSuperTypes="#//ParameterableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" ordered="false"
        lowerBound="1" eType="#//Block" changeable="false" volatile="true" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcePort" ordered="false"
        lowerBound="1" eType="#//OutputPort" eOpposite="#//OutputPort/outgoingConnections"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="virtual" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetPort" ordered="false"
        lowerBound="1" eType="#//InputPort" eOpposite="#//InputPort/incomingConnection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPort" eSuperTypes="#//Port">
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" ordered="false"
        lowerBound="1" eType="#//Output" eOpposite="#//Output/ports"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingConnections" ordered="false"
        upperBound="-1" eType="#//Connection" eOpposite="#//Connection/sourcePort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Output">
    <eStructuralFeatures xsi:type="ecore:EReference" name="specification" ordered="false"
        lowerBound="1" eType="#//OutputSpecification"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" ordered="false"
        lowerBound="1" eType="#//Block" eOpposite="#//Block/outputs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" lowerBound="1" upperBound="-1"
        eType="#//OutputPort" containment="true" eOpposite="#//OutputPort/output"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputSpecification" eSuperTypes="#//IOSpecification"/>
  <eClassifiers xsi:type="ecore:EClass" name="IOSpecification" abstract="true" eSuperTypes="#//NamedElement #//ParameterDescriptorContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimumPortCount" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumPortCount" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="manyPorts" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="virtual" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" lowerBound="1"
        eType="#//IOType" defaultValueLiteral="Scalar"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterDescriptorContainer" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//ParameterDescriptor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IOType">
    <eLiterals name="Scalar"/>
    <eLiterals name="Logic" value="1"/>
    <eLiterals name="Mixed" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Input">
    <eStructuralFeatures xsi:type="ecore:EReference" name="specification" ordered="false"
        lowerBound="1" eType="#//InputSpecification"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" ordered="false"
        lowerBound="1" eType="#//Block" eOpposite="#//Block/inputs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" lowerBound="1" upperBound="-1"
        eType="#//InputPort" containment="true" eOpposite="#//InputPort/input"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputSpecification" eSuperTypes="#//IOSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="directFeedthroughExpression"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BlockType" eSuperTypes="#//NamedElement #//ParameterDescriptorContainer">
    <eOperations name="belongsTo" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="categoryURI" ordered="false" lowerBound="1" eType="#//URI"/>
    </eOperations>
    <eOperations name="belongsTo" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="categoryURI" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
        eType="#//InputSpecification" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
        eType="#//OutputSpecification" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="categories" ordered="false"
        upperBound="-1" eType="#//BlockCategory"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" ordered="false" lowerBound="1"
        eType="#//URI" changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uriAsString" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="virtual" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="structural" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BlockCategory" eSuperTypes="#//NamedElement #//ParameterDescriptorContainer">
    <eOperations name="belongsTo" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="categoryURI" ordered="false" lowerBound="1" eType="#//URI"/>
    </eOperations>
    <eOperations name="belongsTo" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="categoryURI" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parents" ordered="false"
        upperBound="-1" eType="#//BlockCategory"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" ordered="false" lowerBound="1"
        eType="#//URI" changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uriAsString" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="URI" instanceClassName="org.eclipse.emf.common.util.URI"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionParameterDescriptor" eSuperTypes="#//ParameterDescriptor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="redefines" references="#//ParameterDescriptor/%duplicates%/defaultValue"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanParameterDescriptor" eSuperTypes="#//ParameterDescriptor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultBooleanValue" ordered="false"
        lowerBound="1" eType="#//BooleanValue" defaultValueLiteral="False"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BooleanValue">
    <eLiterals name="True"/>
    <eLiterals name="False" value="1"/>
    <eLiterals name="Unspecified" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumerationParameterDescriptor" eSuperTypes="#//ParameterDescriptor">
    <eOperations name="getLiteral" ordered="false" lowerBound="1" eType="#//EnumerationLiteral">
      <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getLiteralByValue" ordered="false" lowerBound="1" eType="#//EnumerationLiteral">
      <eParameters name="value" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedEnumeration" eType="#//Enumeration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inheritedEnumerations"
        upperBound="-1" eType="#//Enumeration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultLiteral" ordered="false"
        lowerBound="1" eType="#//EnumerationLiteral"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exclusive" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enumerationOrder" ordered="false"
        lowerBound="1" eType="#//EnumerationOrder" defaultValueLiteral="OwnedFirst"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="literals" upperBound="-1"
        eType="#//EnumerationLiteral" changeable="false" volatile="true" transient="true"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enumeration" eSuperTypes="#//NamedElement">
    <eAnnotations source="duplicates">
      <contents xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false" volatile="true" transient="true" derived="true">
        <eAnnotations source="redefines" references="#//NamedElement/name"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLiterals" upperBound="-1"
        eType="#//EnumerationLiteral" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inheritedLiterals" upperBound="-1"
        eType="#//EnumerationLiteral"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="literalOrder" ordered="false"
        lowerBound="1" eType="#//EnumerationLiteralOrder" defaultValueLiteral="InheritedFirst"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="literals" upperBound="-1"
        eType="#//EnumerationLiteral" changeable="false" volatile="true" transient="true"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumerationLiteral" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnumerationLiteralOrder">
    <eLiterals name="OwnedFirst"/>
    <eLiterals name="InheritedFirst" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnumerationOrder">
    <eLiterals name="OwnedFirst"/>
    <eLiterals name="InheritedFirst" value="1"/>
  </eClassifiers>
</ecore:EPackage>
