<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dml"
    nsURI="http://www.eclipselabs.org/damos/DML/1.0.0" nsPrefix="dml">
  <eClassifiers xsi:type="ecore:EClass" name="Fragment">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="WellFormedName UniqueComponentNames"/>
    </eAnnotations>
    <eOperations name="getChildren" ordered="false" upperBound="-1" eType="#//Fragment"/>
    <eOperations name="getAllFragmentElements" ordered="false" upperBound="-1" eType="#//FragmentElement"/>
    <eOperations name="getAllComponents" ordered="false" upperBound="-1" eType="#//Component"/>
    <eOperations name="getAllConnections" ordered="false" upperBound="-1" eType="#//Connection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" ordered="false"
        upperBound="-1" eType="#//Component" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fragmentElements" ordered="false"
        upperBound="-1" eType="#//FragmentElement" containment="true" eOpposite="#//FragmentElement/owningFragment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connections" ordered="false"
        upperBound="-1" eType="#//Connection" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" ordered="false"
        eType="#//Fragment"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" abstract="true" eSuperTypes="#//FragmentElement #//CompoundMember">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="WellFormedName"/>
    </eAnnotations>
    <eOperations name="getInputPorts" upperBound="-1" eType="#//InputPort"/>
    <eOperations name="getOutputPorts" upperBound="-1" eType="#//OutputPort"/>
    <eOperations name="getFirstInputPort" ordered="false" lowerBound="1" eType="#//InputPort"/>
    <eOperations name="getFirstOutputPort" ordered="false" lowerBound="1" eType="#//OutputPort"/>
    <eOperations name="getPrimaryInputPorts" upperBound="-1" eType="#//InputPort"/>
    <eOperations name="getPrimaryOutputPorts" upperBound="-1" eType="#//OutputPort"/>
    <eOperations name="isSource" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isSink" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
        eType="#//Input" containment="true" eOpposite="#//Input/component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
        eType="#//Output" containment="true" eOpposite="#//Output/component"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FragmentElement" abstract="true">
    <eOperations name="getEnclosingFragment" lowerBound="1" eType="#//Fragment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningFragment" ordered="false"
        eType="#//Fragment" eOpposite="#//Fragment/fragmentElements"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection" eSuperTypes="#//FragmentElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
        lowerBound="1" eType="#//OutputConnector"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false"
        lowerBound="1" eType="#//InputConnector"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcePort" ordered="false"
        eType="#//OutputPort" volatile="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetPort" ordered="false"
        eType="#//InputPort" volatile="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connector" abstract="true">
    <eOperations name="getConnections" ordered="false" upperBound="-1" eType="#//Connection"/>
    <eOperations name="getConnections" ordered="false" upperBound="-1" eType="#//Connection">
      <eParameters name="context" ordered="false" lowerBound="1" eType="#//Fragment"/>
    </eOperations>
    <eOperations name="getFirstConnection" ordered="false" eType="#//Connection">
      <eParameters name="context" ordered="false" lowerBound="1" eType="#//Fragment"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputConnector" abstract="true" eSuperTypes="#//Connector"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutputConnector" abstract="true" eSuperTypes="#//Connector"/>
  <eClassifiers xsi:type="ecore:EClass" name="Inoutput" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Input" eSuperTypes="#//Inoutput">
    <eOperations name="isDirectFeedthrough" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" upperBound="-1"
        eType="#//InputPort" containment="true" eOpposite="#//InputPort/input"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" ordered="false"
        lowerBound="1" eType="#//Component" eOpposite="#//Component/inputs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Output" eSuperTypes="#//Inoutput">
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" ordered="false"
        lowerBound="1" eType="#//Component" eOpposite="#//Component/outputs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" upperBound="-1"
        eType="#//OutputPort" containment="true" eOpposite="#//OutputPort/output"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port" abstract="true" eSuperTypes="#//Connector">
    <eOperations name="getIndex" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="getComponent" ordered="false" lowerBound="1" eType="#//Component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPort" eSuperTypes="#//Port #//InputConnector">
    <eOperations name="getIncomingConnections" ordered="false" upperBound="-1" eType="#//Connection"/>
    <eOperations name="getIncomingConnection" ordered="false" eType="#//Connection">
      <eParameters name="context" ordered="false" lowerBound="1" eType="#//Fragment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" ordered="false"
        lowerBound="1" eType="#//Input" eOpposite="#//Input/ports"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPort" eSuperTypes="#//Port #//OutputConnector">
    <eOperations name="getOutgoingConnections" ordered="false" upperBound="-1" eType="#//Connection"/>
    <eOperations name="getOutgoingConnections" ordered="false" upperBound="-1" eType="#//Connection">
      <eParameters name="context" ordered="false" lowerBound="1" eType="#//Fragment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" ordered="false"
        lowerBound="1" eType="#//Output" eOpposite="#//Output/ports"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" ordered="false"
        eType="#//SignalSpecification" unsettable="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SignalSpecification" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BlockInoutput" abstract="true" eSuperTypes="#//Inoutput"/>
  <eClassifiers xsi:type="ecore:EClass" name="BlockInput" eSuperTypes="#//Input #//BlockInoutput">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" ordered="false"
        lowerBound="1" eType="#//InputDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BlockOutput" eSuperTypes="#//Output #//BlockInoutput">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" ordered="false"
        lowerBound="1" eType="#//OutputDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InoutputDefinition" abstract="true"
      eSuperTypes="#//ParameterableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimumPortCount" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumPortCount" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultPortCount" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="manyPorts" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" ordered="false"
        eType="#//DataTypeSpecification" unsettable="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputDefinition" eSuperTypes="#//InoutputDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="directFeedthroughPolicy"
        ordered="false" lowerBound="1" eType="#//DirectFeedthroughPolicy" containment="true"
        eOpposite="#//DirectFeedthroughPolicy/inputDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputDefinition" eSuperTypes="#//InoutputDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterableElement" abstract="true">
    <eOperations name="getParameter" ordered="false" eType="#//Parameter">
      <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" abstract="true">
    <eOperations name="getDefaultValue" ordered="false" eType="#//ValueSpecification"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueSpecification" abstract="true">
    <eOperations name="stringValue" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataTypeSpecification" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DirectFeedthroughPolicy" abstract="true">
    <eOperations name="computeDirectFeedthrough" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputDefinition" ordered="false"
        lowerBound="1" eType="#//InputDefinition" eOpposite="#//InputDefinition/directFeedthroughPolicy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterizedElement" abstract="true">
    <eOperations name="getArgument" ordered="false" eType="#//Argument">
      <eParameters name="parameterName" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getArgumentStringValue" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="parameterName" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="#//Argument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Argument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false"
        eType="#//ValueSpecification" unsettable="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" ordered="false"
        lowerBound="1" eType="#//Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionParameter" eSuperTypes="#//Parameter">
    <eOperations name="getPredefinedExpression" ordered="false" lowerBound="1" eType="#//PredefinedExpressionEntry">
      <eParameters name="expression" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getPredefinedExpressionByAlias" ordered="false" lowerBound="1"
        eType="#//PredefinedExpressionEntry">
      <eParameters name="alias" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultExpression" ordered="false"
        eType="#//ExpressionSpecification" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predefinedExpressions"
        upperBound="-1" eType="#//PredefinedExpressionEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" ordered="false"
        eType="#//DataTypeSpecification" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionSpecification" eSuperTypes="#//ValueSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PredefinedExpressionEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false"
        lowerBound="1" eType="#//ExpressionSpecification" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BlockType" eSuperTypes="#//QualifiedElement #//CategorizedElement #//ParameterableElement">
    <eOperations name="newInstance" ordered="false" lowerBound="1" eType="#//Block">
      <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputDefinitions" upperBound="-1"
        eType="#//InputDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputDefinitions" upperBound="-1"
        eType="#//OutputDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behavior" ordered="false"
        eType="#//BehaviorSpecification" unsettable="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QualifiedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifier" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CategorizedElement" abstract="true">
    <eOperations name="belongsTo" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="categoryName" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="belongingCategories" ordered="false"
        upperBound="-1" eType="#//Category"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Category" eSuperTypes="#//QualifiedElement #//CategorizedElement #//ParameterableElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BehaviorSpecification" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="#//Component #//ParameterizedElement">
    <eOperations name="getInput" ordered="false" lowerBound="1" eType="#//BlockInput">
      <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getOutput" ordered="false" lowerBound="1" eType="#//BlockOutput">
      <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1"
        eType="#//BlockType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="#//System"/>
  <eClassifiers xsi:type="ecore:EClass" name="System" eSuperTypes="#//Fragment"/>
  <eClassifiers xsi:type="ecore:EClass" name="BlockPort" abstract="true" eSuperTypes="#//ParameterizedElement #//Port"/>
  <eClassifiers xsi:type="ecore:EClass" name="BlockInputPort" eSuperTypes="#//BlockPort #//InputPort"/>
  <eClassifiers xsi:type="ecore:EClass" name="BlockOutputPort" eSuperTypes="#//OutputPort #//BlockPort"/>
  <eClassifiers xsi:type="ecore:EClass" name="Subsystem" eSuperTypes="#//Component">
    <eOperations name="getRealizations" ordered="false" upperBound="-1" eType="#//SubsystemRealization"/>
    <eOperations name="getRealization" ordered="false" eType="#//SubsystemRealization">
      <eParameters name="context" ordered="false" lowerBound="1" eType="#//Fragment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedInterface" lowerBound="1"
        eType="#//SystemInterface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemInterface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inlets" upperBound="-1"
        eType="#//Inlet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outlets" upperBound="-1"
        eType="#//Outlet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inlet" eSuperTypes="#//Inoutlet"/>
  <eClassifiers xsi:type="ecore:EClass" name="Inoutlet" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" ordered="false"
        lowerBound="1" eType="#//DataTypeSpecification" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Outlet" eSuperTypes="#//Inoutlet"/>
  <eClassifiers xsi:type="ecore:EClass" name="SubsystemRealization" eSuperTypes="#//FragmentElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="MatchingFragment"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedSubsystem" ordered="false"
        lowerBound="1" eType="#//Subsystem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizingFragment" ordered="false"
        lowerBound="1" eType="#//Fragment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inport" eSuperTypes="#//Inoutport"/>
  <eClassifiers xsi:type="ecore:EClass" name="Inoutport" abstract="true" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" ordered="false"
        lowerBound="1" eType="#//DataTypeSpecification" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Outport" eSuperTypes="#//Inoutport"/>
  <eClassifiers xsi:type="ecore:EClass" name="SubsystemInoutput" eSuperTypes="#//Inoutput"/>
  <eClassifiers xsi:type="ecore:EClass" name="SubsystemInput" eSuperTypes="#//Input #//SubsystemInoutput">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inlet" ordered="false"
        lowerBound="1" eType="#//Inlet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubsystemOutput" eSuperTypes="#//Output #//SubsystemInoutput">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outlet" ordered="false"
        lowerBound="1" eType="#//Outlet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanDirectFeedthroughPolicy" eSuperTypes="#//DirectFeedthroughPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="directFeedthrough" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpaqueDataTypeSpecification" eSuperTypes="#//DataTypeSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataType" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpaqueBehaviorSpecification" eSuperTypes="#//BehaviorSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="behavior" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Compound" abstract="true" eSuperTypes="#//FragmentElement #//CompoundMember">
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="#//CompoundMember" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompoundMember" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompoundConnector" abstract="true" eSuperTypes="#//Connector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="compound" lowerBound="1"
        eType="#//Compound" changeable="false" volatile="true" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompoundInputConnector" abstract="true"
      eSuperTypes="#//CompoundConnector #//InputConnector"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompoundOutputConnector" abstract="true"
      eSuperTypes="#//CompoundConnector #//OutputConnector"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalCompound" eSuperTypes="#//Compound">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//ConditionalCompoundCondition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalCompoundCondition" eSuperTypes="#//CompoundInputConnector"/>
</ecore:EPackage>
