<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="executiongraph"
    nsURI="http://www.esmp.org/dsm/ExecutionGraph/1.0.0" nsPrefix="executiongraph">
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionGraph">
    <eOperations name="getNode" ordered="false" lowerBound="1" eType="#//ExecutionNode">
      <eParameters name="blockURI" ordered="false" lowerBound="1" eType="#//URI"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//ExecutionNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialNodes" upperBound="-1"
        eType="#//ExecutionNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
        eType="#//ExecutionEdge" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blockDiagram" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.esmp.dsm.semantic/model/BlockDiagram.ecore#//BlockDiagram"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingEdges" upperBound="-1"
        eType="#//ExecutionEdge" eOpposite="#//ExecutionEdge/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingEdges" upperBound="-1"
        eType="#//ExecutionEdge" eOpposite="#//ExecutionEdge/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.esmp.dsm.semantic/model/BlockDiagram.ecore#//Block"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionEdge">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
        lowerBound="1" eType="#//ExecutionNode" eOpposite="#//ExecutionNode/outgoingEdges"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false"
        lowerBound="1" eType="#//ExecutionNode" eOpposite="#//ExecutionNode/incomingEdges"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="URI" instanceClassName="org.eclipse.emf.common.util.URI"/>
</ecore:EPackage>
