<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simulationmodel"
    nsURI="http://www.eclipselabs.org/damos/SimulationModel/1.0.0" nsPrefix="simulationmodel">
  <eClassifiers xsi:type="ecore:EClass" name="SimulationModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="executionModel" lowerBound="1"
        eType="ecore:EClass ../../org.eclipselabs.damos.execution.executionmodel/model/ExecutionModel.ecore#//ExecutionModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topLevelFragment" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipselabs.damos.dml/model/DML.ecore#//Fragment"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="simulationTime" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
</ecore:EPackage>
