<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simulationmodel"
    nsURI="http://www.eclipselabs.org/damos/2011/SimulationModel" nsPrefix="simulationmodel">
  <eClassifiers xsi:type="ecore:EClass" name="SimulationModel">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ValidSimulationTime"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executionModel" eType="ecore:EClass ../../org.eclipselabs.damos.execution.executionmodel/model/ExecutionModel.ecore#//ExecutionModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topLevelFragment" eType="ecore:EClass ../../org.eclipselabs.damos.dml/model/DML.ecore#//Fragment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="simulationTime" eType="ecore:EClass ../../org.eclipselabs.damos.mscript/model/Mscript.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="solverConfiguration" eType="#//SolverConfiguration"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolverType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configurationDefinition"
        eType="#//SolverConfigurationDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolverConfigurationDefinition">
    <eOperations name="getParameter" eType="#//SolverParameter">
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//SolverParameter" containment="true" eOpposite="#//SolverParameter/configurationDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolverParameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="configurationDefinition"
        lowerBound="1" eType="#//SolverConfigurationDefinition" eOpposite="#//SolverConfigurationDefinition/parameters"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolverConfiguration">
    <eOperations name="getArgument" eType="#//SolverArgument">
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getArgumentValue" eType="ecore:EClass ../../org.eclipselabs.damos.mscript/model/Mscript.ecore#//Expression">
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//SolverType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="#//SolverArgument" containment="true" eOpposite="#//SolverArgument/configuration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolverArgument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" eType="#//SolverConfiguration"
        eOpposite="#//SolverConfiguration/arguments"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" eType="#//SolverParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass ../../org.eclipselabs.damos.mscript/model/Mscript.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
