/*
* generated by Xtext
*/
package org.eclipselabs.damos.execution.executionmodel.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipselabs.damos.execution.executionmodel.services.ExecutionModelGrammarAccess;

public class ExecutionModelParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ExecutionModelGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipselabs.damos.execution.executionmodel.parser.antlr.internal.InternalExecutionModelParser createParser(XtextTokenStream stream) {
		return new org.eclipselabs.damos.execution.executionmodel.parser.antlr.internal.InternalExecutionModelParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "ExecutionModel";
	}
	
	public ExecutionModelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ExecutionModelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
