/*
 * generated by Xtext
 */
package org.eclipselabs.damos.dconfig;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.conversion.impl.AbstractIDValueConverter;
import org.eclipse.xtext.conversion.impl.QualifiedNameValueConverter;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.scoping.IGlobalScopeProvider;
import org.eclipse.xtext.scoping.IScopeProvider;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;
import org.eclipselabs.damos.dconfig.conversion.DconfigTerminalConverters;
import org.eclipselabs.damos.dconfig.naming.DconfigQualifiedNameProvider;
import org.eclipselabs.damos.dconfig.scoping.DconfigGlobalScopeProvider;
import org.eclipselabs.damos.dconfig.scoping.DconfigImportedNamespaceScopeProvider;
import org.eclipselabs.damos.mscript.conversion.MscriptIDValueConverter;
import org.eclipselabs.damos.mscript.conversion.MscriptQualifiedNameValueConverter;

import com.google.inject.name.Names;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DconfigRuntimeModule extends org.eclipselabs.damos.dconfig.AbstractDconfigRuntimeModule {

	public Class<? extends AbstractIDValueConverter> bindAbstractIDValueConverter() {
		return MscriptIDValueConverter.class;
	}

	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
		return DconfigTerminalConverters.class;
	}
	
	@Override
	public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
		return DconfigGlobalScopeProvider.class;
	}
	
	public Class<? extends QualifiedNameValueConverter> bindQualifiedNameValueConverter() {
		return MscriptQualifiedNameValueConverter.class;
	}

	@Override
	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return DconfigQualifiedNameProvider.class;
	}

	public void configureIScopeProviderDelegate(com.google.inject.Binder binder) {
		binder.bind(IScopeProvider.class).annotatedWith(Names.named(AbstractDeclarativeScopeProvider.NAMED_DELEGATE)).to(DconfigImportedNamespaceScopeProvider.class);
	}

}
