/*
* generated by Xtext
*/
package org.eclipselabs.damos.mscript;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MscriptUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.eclipselabs.damos.mscript.ui.internal.MscriptActivator.getInstance().getInjector("org.eclipselabs.damos.mscript.Mscript");
	}
	
}
