/*
* generated by Xtext
*/
package org.eclipselabs.damos.execution.executionmodel.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class ExecutionModelOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
