/*
* generated by Xtext
*/
package org.eclipse.damos.dconfig.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DconfigAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/eclipse/damos/dconfig/parser/antlr/internal/InternalDconfig.tokens");
	}
}
