/*
* generated by Xtext
*/
package org.eclipselabs.damos.mscript.ui.contentassist;

import org.eclipselabs.damos.mscript.ui.contentassist.AbstractMscriptProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class MscriptProposalProvider extends AbstractMscriptProposalProvider {

}
