/*
 * generated by Xtext
 */
package org.eclipselabs.damos.mscript;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.linking.ILinker;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.scoping.IGlobalScopeProvider;
import org.eclipselabs.damos.mscript.conversion.MscriptTerminalConverters;
import org.eclipselabs.damos.mscript.linking.MscriptLinker;
import org.eclipselabs.damos.mscript.naming.QualifiedNameConverter;
import org.eclipselabs.damos.mscript.naming.QualifiedNameProvider;
import org.eclipselabs.damos.mscript.scoping.GlobalScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MscriptRuntimeModule extends org.eclipselabs.damos.mscript.AbstractMscriptRuntimeModule {

	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
		return MscriptTerminalConverters.class;
	}
	
	/* (non-Javadoc)
	 * @see org.eclipselabs.mscript.language.AbstractMscriptRuntimeModule#bindIGlobalScopeProvider()
	 */
	@Override
	public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
		return GlobalScopeProvider.class;
	}
	
	/* (non-Javadoc)
	 * @see org.eclipselabs.mscript.language.AbstractMscriptRuntimeModule#bindIQualifiedNameProvider()
	 */
	@Override
	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return QualifiedNameProvider.class;
	}
	
	public Class<? extends org.eclipse.xtext.naming.IQualifiedNameConverter> bindIQualifiedNameConverter() {
		return QualifiedNameConverter.class;
	}

	/* (non-Javadoc)
	 * @see org.eclipse.xtext.service.DefaultRuntimeModule#bindILinker()
	 */
	@Override
	public Class<? extends ILinker> bindILinker() {
		// TODO: Remove this binding, use LazyLinker instead
		return MscriptLinker.class;
	}

}
