/*
 * generated by Xtext
 */
package org.eclipselabs.damos.mscript.computationmodel;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipselabs.damos.mscript.computationmodel.conversion.ComputationModelTerminalConverters;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ComputationModelRuntimeModule extends org.eclipselabs.damos.mscript.computationmodel.AbstractComputationModelRuntimeModule {

	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
		return ComputationModelTerminalConverters.class;
	}

}
