/*
* generated by Xtext
*/
package org.eclipselabs.damos.simulation.simulationmodel.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class SimulationModelOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
