/*
 * generated by Xtext
 */
package org.eclipselabs.damos.dscript.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipselabs.damos.dscript.ui.internal.DscriptActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DscriptExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DscriptActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DscriptActivator.getInstance().getInjector(DscriptActivator.ORG_ECLIPSELABS_DAMOS_DSCRIPT_DSCRIPT);
	}
	
}
