/*
* generated by Xtext
*/
package org.eclipselabs.damos.codegen.c.cgenmodel.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipselabs.damos.codegen.c.cgenmodel.services.CGenModelGrammarAccess;

public class CGenModelParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CGenModelGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipselabs.damos.codegen.c.cgenmodel.parser.antlr.internal.InternalCGenModelParser createParser(XtextTokenStream stream) {
		return new org.eclipselabs.damos.codegen.c.cgenmodel.parser.antlr.internal.InternalCGenModelParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "GenModel";
	}
	
	public CGenModelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CGenModelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
