<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="computation" nsURI="http://www.eclipselabs.org/damos/mscript/2011/ComputationModel"
    nsPrefix="computation">
  <eClassifiers xsi:type="ecore:EClass" name="ComputationModel">
    <eOperations name="getNumberFormatMapping" ordered="false" eType="#//NumberFormatMapping">
      <eParameters name="type" ordered="false" lowerBound="1" eType="ecore:EClass Mscript.ecore#//Type"/>
    </eOperations>
    <eOperations name="getNumberFormat" ordered="false" eType="#//NumberFormat">
      <eParameters name="type" ordered="false" lowerBound="1" eType="ecore:EClass Mscript.ecore#//Type"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="numberFormatMappings" ordered="false"
        upperBound="-1" eType="#//NumberFormatMapping" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumberFormatMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeSpecifier" ordered="false"
        eType="ecore:EClass Mscript.ecore#//TypeSpecifier" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="numberFormat" ordered="false"
        eType="#//NumberFormat" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumberFormat" abstract="true">
    <eOperations name="isEquivalentTo" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="other" lowerBound="1" eType="#//NumberFormat"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FixedPointFormat" eSuperTypes="#//NumberFormat">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="predefinedKind" eType="#//PredefinedFixedPointFormatKind"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unsigned" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="integerLength" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fractionLength" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wordSize" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="slope" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="1.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bias" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="saturate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PredefinedFixedPointFormatKind">
    <eLiterals name="None"/>
    <eLiterals name="Int8" value="1"/>
    <eLiterals name="Int16" value="2"/>
    <eLiterals name="Int32" value="3"/>
    <eLiterals name="Int64" value="4"/>
    <eLiterals name="Int128" value="5"/>
    <eLiterals name="UInt8" value="6"/>
    <eLiterals name="UInt16" value="7"/>
    <eLiterals name="UInt32" value="8"/>
    <eLiterals name="UInt64" value="9"/>
    <eLiterals name="UInt128" value="10"/>
    <eLiterals name="Fract8" value="11"/>
    <eLiterals name="Fract16" value="12"/>
    <eLiterals name="Fract32" value="13"/>
    <eLiterals name="Fract64" value="14"/>
    <eLiterals name="Fract128" value="15"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FloatingPointFormat" eSuperTypes="#//NumberFormat">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" ordered="false" lowerBound="1"
        eType="#//FloatingPointFormatKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FloatingPointFormatKind">
    <eLiterals name="Binary16"/>
    <eLiterals name="Binary32" value="1"/>
    <eLiterals name="Binary64" value="2"/>
    <eLiterals name="Binary128" value="3"/>
    <eLiterals name="Decimal32" value="4"/>
    <eLiterals name="Decimal64" value="5"/>
    <eLiterals name="Decimal128" value="6"/>
  </eClassifiers>
</ecore:EPackage>
