<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="il"
    nsURI="http://www.eclipselabs.org/damos/mscript/2011/IL" nsPrefix="il">
  <eClassifiers xsi:type="ecore:EClass" name="ILFunctionDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionDefinition" lowerBound="1"
        eType="ecore:EClass Mscript.ecore#//FunctionDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stateful" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initializationCompound"
        eType="ecore:EClass Mscript.ecore#//Compound" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="computationCompounds" upperBound="-1"
        eType="#//ComputationCompound" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComputationCompound" eSuperTypes="Mscript.ecore#//Compound">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
        eType="ecore:EClass Mscript.ecore#//InputParameterDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
        eType="ecore:EClass Mscript.ecore#//OutputParameterDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvalidExpression" eSuperTypes="Mscript.ecore#//Expression"/>
</ecore:EPackage>
