/*
 * generated by Xtext
 */
package org.eclipselabs.damos.simulation.simulationmodel.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SimulationModelExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.eclipselabs.damos.simulation.simulationmodel.ui.internal.SimulationModelActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.eclipselabs.damos.simulation.simulationmodel.ui.internal.SimulationModelActivator.getInstance().getInjector("org.eclipselabs.damos.simulation.simulationmodel.SimulationModel");
	}
	
}
