/*
 * generated by Xtext
 */
package com.yakindu.statechart;

/**
 * Use this class to register components to be used within the IDE.
 */
public class WorkflowUiModule extends com.yakindu.statechart.AbstractWorkflowUiModule {

}
