/*
* generated by Xtext
*/
package org.eclipselabs.damos.codegen.c.cgenmodel.ui.contentassist;

import org.eclipselabs.damos.codegen.c.cgenmodel.ui.contentassist.AbstractCGenModelProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class CGenModelProposalProvider extends AbstractCGenModelProposalProvider {

}
