/*
* generated by Xtext
*/
package org.eclipselabs.damos.dmltext.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class DMLTextProposalProvider extends AbstractDMLTextProposalProvider {

}
