<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="executionmodel"
    nsURI="http://www.eclipselabs.org/damos/ExecutionModel/1.0.0" nsPrefix="executionmodel">
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionModel" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sampleTime" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="computationModel" eType="ecore:EClass ../../org.eclipselabs.mscript.computation.computationmodel/model/ComputationModel.ecore#//ComputationModel"/>
  </eClassifiers>
</ecore:EPackage>
