/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipselabs.damos.dml.edit.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import org.eclipselabs.damos.dml.util.DMLAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class DMLItemProviderAdapterFactory extends DMLAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public DMLItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.Fragment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FragmentItemProvider fragmentItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.Fragment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFragmentAdapter() {
		if (fragmentItemProvider == null) {
			fragmentItemProvider = new FragmentItemProvider(this);
		}

		return fragmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.Input} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InputItemProvider inputItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.Input}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInputAdapter() {
		if (inputItemProvider == null) {
			inputItemProvider = new InputItemProvider(this);
		}

		return inputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.InputPort} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InputPortItemProvider inputPortItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.InputPort}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInputPortAdapter() {
		if (inputPortItemProvider == null) {
			inputPortItemProvider = new InputPortItemProvider(this);
		}

		return inputPortItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.Connection} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConnectionItemProvider connectionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.Connection}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConnectionAdapter() {
		if (connectionItemProvider == null) {
			connectionItemProvider = new ConnectionItemProvider(this);
		}

		return connectionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.OutputPort} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OutputPortItemProvider outputPortItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.OutputPort}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOutputPortAdapter() {
		if (outputPortItemProvider == null) {
			outputPortItemProvider = new OutputPortItemProvider(this);
		}

		return outputPortItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.Output} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OutputItemProvider outputItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.Output}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOutputAdapter() {
		if (outputItemProvider == null) {
			outputItemProvider = new OutputItemProvider(this);
		}

		return outputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.BlockInput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BlockInputItemProvider blockInputItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.BlockInput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBlockInputAdapter() {
		if (blockInputItemProvider == null) {
			blockInputItemProvider = new BlockInputItemProvider(this);
		}

		return blockInputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.InputDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InputDefinitionItemProvider inputDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.InputDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInputDefinitionAdapter() {
		if (inputDefinitionItemProvider == null) {
			inputDefinitionItemProvider = new InputDefinitionItemProvider(this);
		}

		return inputDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.BlockOutput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BlockOutputItemProvider blockOutputItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.BlockOutput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBlockOutputAdapter() {
		if (blockOutputItemProvider == null) {
			blockOutputItemProvider = new BlockOutputItemProvider(this);
		}

		return blockOutputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.OutputDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OutputDefinitionItemProvider outputDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.OutputDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOutputDefinitionAdapter() {
		if (outputDefinitionItemProvider == null) {
			outputDefinitionItemProvider = new OutputDefinitionItemProvider(this);
		}

		return outputDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.Argument} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArgumentItemProvider argumentItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.Argument}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArgumentAdapter() {
		if (argumentItemProvider == null) {
			argumentItemProvider = new ArgumentItemProvider(this);
		}

		return argumentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.ExpressionParameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExpressionParameterItemProvider expressionParameterItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.ExpressionParameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExpressionParameterAdapter() {
		if (expressionParameterItemProvider == null) {
			expressionParameterItemProvider = new ExpressionParameterItemProvider(this);
		}

		return expressionParameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.ExpressionSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExpressionSpecificationItemProvider expressionSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.ExpressionSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExpressionSpecificationAdapter() {
		if (expressionSpecificationItemProvider == null) {
			expressionSpecificationItemProvider = new ExpressionSpecificationItemProvider(this);
		}

		return expressionSpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.PredefinedExpressionEntry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PredefinedExpressionEntryItemProvider predefinedExpressionEntryItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.PredefinedExpressionEntry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPredefinedExpressionEntryAdapter() {
		if (predefinedExpressionEntryItemProvider == null) {
			predefinedExpressionEntryItemProvider = new PredefinedExpressionEntryItemProvider(this);
		}

		return predefinedExpressionEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.BlockType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BlockTypeItemProvider blockTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.BlockType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBlockTypeAdapter() {
		if (blockTypeItemProvider == null) {
			blockTypeItemProvider = new BlockTypeItemProvider(this);
		}

		return blockTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.Category} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CategoryItemProvider categoryItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.Category}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCategoryAdapter() {
		if (categoryItemProvider == null) {
			categoryItemProvider = new CategoryItemProvider(this);
		}

		return categoryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.Block} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BlockItemProvider blockItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.Block}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBlockAdapter() {
		if (blockItemProvider == null) {
			blockItemProvider = new BlockItemProvider(this);
		}

		return blockItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.Model} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModelItemProvider modelItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.Model}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModelAdapter() {
		if (modelItemProvider == null) {
			modelItemProvider = new ModelItemProvider(this);
		}

		return modelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.System} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SystemItemProvider systemItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.System}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSystemAdapter() {
		if (systemItemProvider == null) {
			systemItemProvider = new SystemItemProvider(this);
		}

		return systemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.BlockInputPort} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BlockInputPortItemProvider blockInputPortItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.BlockInputPort}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBlockInputPortAdapter() {
		if (blockInputPortItemProvider == null) {
			blockInputPortItemProvider = new BlockInputPortItemProvider(this);
		}

		return blockInputPortItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.BlockOutputPort} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BlockOutputPortItemProvider blockOutputPortItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.BlockOutputPort}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBlockOutputPortAdapter() {
		if (blockOutputPortItemProvider == null) {
			blockOutputPortItemProvider = new BlockOutputPortItemProvider(this);
		}

		return blockOutputPortItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.Subsystem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubsystemItemProvider subsystemItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.Subsystem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubsystemAdapter() {
		if (subsystemItemProvider == null) {
			subsystemItemProvider = new SubsystemItemProvider(this);
		}

		return subsystemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.SystemInterface} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SystemInterfaceItemProvider systemInterfaceItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.SystemInterface}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSystemInterfaceAdapter() {
		if (systemInterfaceItemProvider == null) {
			systemInterfaceItemProvider = new SystemInterfaceItemProvider(this);
		}

		return systemInterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.Inlet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InletItemProvider inletItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.Inlet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInletAdapter() {
		if (inletItemProvider == null) {
			inletItemProvider = new InletItemProvider(this);
		}

		return inletItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.Outlet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OutletItemProvider outletItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.Outlet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOutletAdapter() {
		if (outletItemProvider == null) {
			outletItemProvider = new OutletItemProvider(this);
		}

		return outletItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.SubsystemRealization} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubsystemRealizationItemProvider subsystemRealizationItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.SubsystemRealization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubsystemRealizationAdapter() {
		if (subsystemRealizationItemProvider == null) {
			subsystemRealizationItemProvider = new SubsystemRealizationItemProvider(this);
		}

		return subsystemRealizationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.Inport} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InportItemProvider inportItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.Inport}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInportAdapter() {
		if (inportItemProvider == null) {
			inportItemProvider = new InportItemProvider(this);
		}

		return inportItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.Outport} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OutportItemProvider outportItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.Outport}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOutportAdapter() {
		if (outportItemProvider == null) {
			outportItemProvider = new OutportItemProvider(this);
		}

		return outportItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.SubsystemInoutput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubsystemInoutputItemProvider subsystemInoutputItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.SubsystemInoutput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubsystemInoutputAdapter() {
		if (subsystemInoutputItemProvider == null) {
			subsystemInoutputItemProvider = new SubsystemInoutputItemProvider(this);
		}

		return subsystemInoutputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.SubsystemInput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubsystemInputItemProvider subsystemInputItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.SubsystemInput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubsystemInputAdapter() {
		if (subsystemInputItemProvider == null) {
			subsystemInputItemProvider = new SubsystemInputItemProvider(this);
		}

		return subsystemInputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.SubsystemOutput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubsystemOutputItemProvider subsystemOutputItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.SubsystemOutput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubsystemOutputAdapter() {
		if (subsystemOutputItemProvider == null) {
			subsystemOutputItemProvider = new SubsystemOutputItemProvider(this);
		}

		return subsystemOutputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.BooleanDirectFeedthroughPolicy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BooleanDirectFeedthroughPolicyItemProvider booleanDirectFeedthroughPolicyItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.BooleanDirectFeedthroughPolicy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBooleanDirectFeedthroughPolicyAdapter() {
		if (booleanDirectFeedthroughPolicyItemProvider == null) {
			booleanDirectFeedthroughPolicyItemProvider = new BooleanDirectFeedthroughPolicyItemProvider(this);
		}

		return booleanDirectFeedthroughPolicyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.OpaqueDataTypeSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OpaqueDataTypeSpecificationItemProvider opaqueDataTypeSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.OpaqueDataTypeSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOpaqueDataTypeSpecificationAdapter() {
		if (opaqueDataTypeSpecificationItemProvider == null) {
			opaqueDataTypeSpecificationItemProvider = new OpaqueDataTypeSpecificationItemProvider(this);
		}

		return opaqueDataTypeSpecificationItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (fragmentItemProvider != null) fragmentItemProvider.dispose();
		if (inputItemProvider != null) inputItemProvider.dispose();
		if (inputPortItemProvider != null) inputPortItemProvider.dispose();
		if (connectionItemProvider != null) connectionItemProvider.dispose();
		if (outputPortItemProvider != null) outputPortItemProvider.dispose();
		if (outputItemProvider != null) outputItemProvider.dispose();
		if (blockInputItemProvider != null) blockInputItemProvider.dispose();
		if (inputDefinitionItemProvider != null) inputDefinitionItemProvider.dispose();
		if (blockOutputItemProvider != null) blockOutputItemProvider.dispose();
		if (outputDefinitionItemProvider != null) outputDefinitionItemProvider.dispose();
		if (argumentItemProvider != null) argumentItemProvider.dispose();
		if (expressionParameterItemProvider != null) expressionParameterItemProvider.dispose();
		if (expressionSpecificationItemProvider != null) expressionSpecificationItemProvider.dispose();
		if (predefinedExpressionEntryItemProvider != null) predefinedExpressionEntryItemProvider.dispose();
		if (blockTypeItemProvider != null) blockTypeItemProvider.dispose();
		if (categoryItemProvider != null) categoryItemProvider.dispose();
		if (blockItemProvider != null) blockItemProvider.dispose();
		if (modelItemProvider != null) modelItemProvider.dispose();
		if (systemItemProvider != null) systemItemProvider.dispose();
		if (blockInputPortItemProvider != null) blockInputPortItemProvider.dispose();
		if (blockOutputPortItemProvider != null) blockOutputPortItemProvider.dispose();
		if (subsystemItemProvider != null) subsystemItemProvider.dispose();
		if (systemInterfaceItemProvider != null) systemInterfaceItemProvider.dispose();
		if (inletItemProvider != null) inletItemProvider.dispose();
		if (outletItemProvider != null) outletItemProvider.dispose();
		if (subsystemRealizationItemProvider != null) subsystemRealizationItemProvider.dispose();
		if (inportItemProvider != null) inportItemProvider.dispose();
		if (outportItemProvider != null) outportItemProvider.dispose();
		if (subsystemInoutputItemProvider != null) subsystemInoutputItemProvider.dispose();
		if (subsystemInputItemProvider != null) subsystemInputItemProvider.dispose();
		if (subsystemOutputItemProvider != null) subsystemOutputItemProvider.dispose();
		if (booleanDirectFeedthroughPolicyItemProvider != null) booleanDirectFeedthroughPolicyItemProvider.dispose();
		if (opaqueDataTypeSpecificationItemProvider != null) opaqueDataTypeSpecificationItemProvider.dispose();
	}

}
