/*
 * generated by Xtext
 */
package com.yakindu.statechart.model.expressions.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class StatechartExpressionsUiModule extends com.yakindu.statechart.model.expressions.ui.AbstractStatechartExpressionsUiModule {
	public StatechartExpressionsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
