/*
* generated by Xtext
*/
package org.eclipselabs.damos.mscript.computationmodel.ui.contentassist;

import org.eclipselabs.damos.mscript.computationmodel.ui.contentassist.AbstractComputationModelProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ComputationModelProposalProvider extends AbstractComputationModelProposalProvider {

}
