/*
* generated by Xtext
*/
package com.yakindu.statechart.model.expressions.ui.contentassist;

import com.yakindu.statechart.model.expressions.ui.contentassist.AbstractStatechartExpressionsProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class StatechartExpressionsProposalProvider extends AbstractStatechartExpressionsProposalProvider {

}
