/**
 * Copyright (c) 2010 committers of YAKINDU and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     committers of YAKINDU - initial API and implementation
 */
/*
 * generated by Xtext
 */
package com.yakindu.statechart.model.expressions;

/**
 * Use this class to register components to be used within the IDE.
 */
public class StatechartExpressionsUiModule extends com.yakindu.statechart.model.expressions.AbstractStatechartExpressionsUiModule {

}
