/*
 * generated by Xtext
 */
package org.eclipselabs.damos.dconfig.scoping;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import org.eclipse.xtext.scoping.impl.SimpleScope;
import org.eclipselabs.damos.dconfig.BindingBody;
import org.eclipselabs.damos.dconfig.ComponentPath;
import org.eclipselabs.damos.dconfig.ComponentReference;
import org.eclipselabs.damos.dconfig.ComputationProperty;
import org.eclipselabs.damos.dconfig.Configuration;
import org.eclipselabs.damos.dconfig.DconfigPackage;
import org.eclipselabs.damos.dconfig.FragmentConfiguration;
import org.eclipselabs.damos.dconfig.RootSystemConfiguration;
import org.eclipselabs.damos.dconfig.SelectionProperty;
import org.eclipselabs.damos.dconfig.SelectionPropertyBody;
import org.eclipselabs.damos.dconfig.SelectionPropertyDeclaration;
import org.eclipselabs.damos.dconfig.SelectionPropertyOption;
import org.eclipselabs.damos.dconfig.SimplePropertyDeclaration;
import org.eclipselabs.damos.dconfig.SubsystemConfiguration;
import org.eclipselabs.damos.dconfig.SystemConfiguration;
import org.eclipselabs.damos.dml.Component;
import org.eclipselabs.damos.dml.DMLPackage;
import org.eclipselabs.damos.dml.Fragment;
import org.eclipselabs.damos.dml.FragmentElement;
import org.eclipselabs.damos.dml.Subsystem;
import org.eclipselabs.damos.dml.SubsystemRealization;
import org.eclipselabs.damos.dml.util.DMLUtil;
import org.eclipselabs.damos.mscript.computation.ComputationPackage;
import org.eclipselabs.damos.mscript.scoping.MscriptScopeProvider;

import com.google.common.base.Predicate;
import com.google.common.collect.Iterables;
import com.google.common.collect.Iterators;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class DconfigScopeProvider extends MscriptScopeProvider {

	private static final Predicate<FragmentElement> COMPONENT_PREDICATE = new Predicate<FragmentElement>() {
		
		public boolean apply(FragmentElement input) {
			return input instanceof Component;
		}
		
	};
	
	public IScope scope_Configuration_baseConfiguration(Configuration context, EReference reference) {
		return new SimpleScope(Scopes.selectCompatible(getDelegate().getScope(context, reference).getAllElements(),
				DconfigPackage.eINSTANCE.getConfiguration()));
	}
	
	public IScope scope_SimpleProperty_declaration(Configuration context, EReference reference) {
		return new SimpleScope(Scopes.selectCompatible(getDelegate().getScope(context, reference).getAllElements(),
				DconfigPackage.eINSTANCE.getSimplePropertyDeclaration()));
	}

	public IScope scope_SimpleProperty_declaration(SelectionPropertyBody context, EReference reference) {
		return Scopes.scopeFor(Iterables.filter(context.getOwner().getSelection().getPropertyDeclarations(), SimplePropertyDeclaration.class));
	}

	public IScope scope_SimpleProperty_declaration(BindingBody context, EReference reference) {
		return Scopes.scopeFor(Iterables.filter(context.getOwner().getTarget().getResourceDeclaration().getPropertyDeclarations(), SimplePropertyDeclaration.class));
	}

	public IScope scope_SelectionProperty_declaration(Configuration context, EReference reference) {
		return new SimpleScope(Scopes.selectCompatible(getDelegate().getScope(context, reference).getAllElements(),
				DconfigPackage.eINSTANCE.getSelectionPropertyDeclaration()));
	}
	
	public IScope scope_SelectionProperty_declaration(SelectionPropertyBody context, EReference reference) {
		return Scopes.scopeFor(Iterables.filter(context.getOwner().getSelection().getPropertyDeclarations(), SelectionPropertyDeclaration.class));
	}

	public IScope scope_SelectionProperty_declaration(BindingBody context, EReference reference) {
		return Scopes.scopeFor(Iterables.filter(context.getOwner().getTarget().getResourceDeclaration().getPropertyDeclarations(), SelectionPropertyDeclaration.class));
	}

	public IScope scope_SelectionProperty_selection(final SelectionProperty context, EReference reference) {
		Iterable<IEObjectDescription> elements = getDelegate().getScope(context, reference).getAllElements();
		Iterable<IEObjectDescription> filteredElements = Iterables.filter(elements, new Predicate<IEObjectDescription>() {

			public boolean apply(IEObjectDescription input) {
				EObject eObjectOrProxy = input.getEObjectOrProxy();
				if (eObjectOrProxy instanceof SelectionPropertyOption) {
					eObjectOrProxy = EcoreUtil.resolve(eObjectOrProxy, context);
					if (!eObjectOrProxy.eIsProxy()) {
						SelectionPropertyOption option = (SelectionPropertyOption) eObjectOrProxy;
						if (option.getTarget() == context.getDeclaration()) {
							return true;
						}
					}
				}
				return false;
			}
			
		});
		return new SimpleScope(filteredElements);
	}
	
	public IScope scope_RootSystemConfiguration_contextFragment(RootSystemConfiguration context, EReference reference) {
		return new SimpleScope(Scopes.selectCompatible(getDelegate().getScope(context, reference).getAllElements(),
				DMLPackage.eINSTANCE.getFragment()));
	}

	public IScope scope_FragmentConfiguration_startFragment(SystemConfiguration context, EReference reference) {
		Fragment contextFragment = getContextFragment(context);
		if (contextFragment != null) {
			List<Fragment> fragments = new ArrayList<Fragment>();
			while (contextFragment != null) {
				fragments.add(contextFragment);
				contextFragment = contextFragment.getParent();
			}
			return Scopes.scopeFor(fragments);
		}
		return IScope.NULLSCOPE;
	}

	public IScope scope_FragmentConfiguration_endFragment(FragmentConfiguration context, EReference reference) {
		SystemConfiguration systemConfiguration = DMLUtil.getOwner(context, SystemConfiguration.class);
		if (systemConfiguration == null) {
			return IScope.NULLSCOPE;
		}
		Fragment startFragment = context.getStartFragment();
		Fragment contextFragment = getContextFragment(systemConfiguration);
		if (contextFragment != null) {
			List<Fragment> fragments = new ArrayList<Fragment>();
			while (contextFragment != null) {
				if (startFragment == contextFragment) {
					startFragment = null;
				}
				if (startFragment == null) {
					fragments.add(contextFragment);
				}
				contextFragment = contextFragment.getParent();
			}
			return Scopes.scopeFor(fragments);
		}
		return IScope.NULLSCOPE;
	}

	public IScope scope_ComponentConfiguration_component(SystemConfiguration context, EReference reference) {
		Fragment contextFragment = getContextFragment(context);
		if (contextFragment == null) {
			return IScope.NULLSCOPE;
		}

		return Scopes.scopeFor(Iterables.filter(getAllFragmentElements(contextFragment), Component.class));
	}

	public IScope scope_SubsystemConfiguration_subsystem(SubsystemConfiguration context, EReference reference) {
		SystemConfiguration enclosingSystemConfiguration = context.getParent();
		if (enclosingSystemConfiguration == null) {
			return IScope.NULLSCOPE;
		}

		Fragment contextFragment = getContextFragment(enclosingSystemConfiguration);
		if (contextFragment == null) {
			return IScope.NULLSCOPE;
		}
		
		return Scopes.scopeFor(Iterables.filter(getAllFragmentElements(contextFragment), Subsystem.class));
	}
	
	public IScope scope_ComputationProperty_computationModel(ComputationProperty context, EReference reference) {
		return new SimpleScope(Scopes.selectCompatible(getDelegate().getScope(context, reference).getAllElements(),
				ComputationPackage.eINSTANCE.getComputationModel()));
	}
	
	public IScope scope_BindingResourceReference_resourceDeclaration(SelectionProperty context, EReference reference) {
		if (DMLUtil.isResolved(context.getSelection())) {
			return Scopes.scopeFor(context.getSelection().getResourceDeclarations());
		}
		return IScope.NULLSCOPE;
	}

	public IScope scope_ComponentReference_component(Configuration context, EReference reference) {
		Fragment contextFragment = context.getContextFragment();
		if (DMLUtil.isResolved(contextFragment)) {
			return Scopes.scopeFor(Iterables.filter(getAllFragmentElements(contextFragment), COMPONENT_PREDICATE));
		}
		return IScope.NULLSCOPE;
	}

	public IScope scope_ComponentReference_component(ComponentPath context, EReference reference) {
		return doScope_ComponentReference_component(context, null);
	}

	public IScope scope_ComponentReference_component(ComponentReference context, EReference reference) {
		return doScope_ComponentReference_component((ComponentPath) context.eContainer(), context);
	}

	private IScope doScope_ComponentReference_component(ComponentPath componentPath, ComponentReference excluding) {
		Configuration configuration = DMLUtil.getOwner(componentPath, Configuration.class);
		if (configuration == null) {
			return IScope.NULLSCOPE;
		}

		Fragment contextFragment = configuration.getContextFragment();
		if (!DMLUtil.isResolved(contextFragment)) {
			return IScope.NULLSCOPE;
		}
		
		for (ComponentReference componentReference : componentPath.getReferences()) {
			if (componentReference == excluding) {
				break;
			}
			
			Component component = componentReference.getComponent();
			
			if (!DMLUtil.isResolved(component)) {
				break;
			}

			if (!(component instanceof Subsystem)) {
				return IScope.NULLSCOPE;
			}
			
			SubsystemRealization realization = ((Subsystem) component).getRealization(contextFragment);
			if (!DMLUtil.isResolved(realization) || !DMLUtil.isResolved(realization.getRealizingFragment())) {
				return IScope.NULLSCOPE;
			}
			
			contextFragment = realization.getRealizingFragment();
		}
		
		return Scopes.scopeFor(Iterables.filter(getAllFragmentElements(contextFragment), COMPONENT_PREDICATE));
	}
	
	private Fragment getContextFragment(SystemConfiguration systemConfiguration) {
		if (systemConfiguration instanceof RootSystemConfiguration) {
			return ((RootSystemConfiguration) systemConfiguration).getContextFragment();
		}
	
		List<SystemConfiguration> enclosingSystemConfigurations = new ArrayList<SystemConfiguration>();
		enclosingSystemConfigurations.add(systemConfiguration);
		
		while (systemConfiguration instanceof SubsystemConfiguration) {
			systemConfiguration = ((SubsystemConfiguration) systemConfiguration).getParent();
			enclosingSystemConfigurations.add(systemConfiguration);
		}
		
		SystemConfiguration rootSystemConfiguration = enclosingSystemConfigurations.get(enclosingSystemConfigurations.size() - 1);
		if (!(rootSystemConfiguration instanceof RootSystemConfiguration)) {
			return null;
		}
		
		Fragment contextFragment = ((RootSystemConfiguration) rootSystemConfiguration).getContextFragment();
		
		for (int i = enclosingSystemConfigurations.size() - 2; i >= 0; --i) {
			SystemConfiguration next = enclosingSystemConfigurations.get(i);
			if (!(next instanceof SubsystemConfiguration)) {
				return null;
			}
			SubsystemRealization realization = ((SubsystemConfiguration) next).getSubsystem().getRealization(contextFragment);
			if (realization == null) {
				return null;
			}
			contextFragment = realization.getRealizingFragment();
			if (contextFragment == null) {
				return null;
			}
		}
		
		return contextFragment;
	}

	private Iterable<FragmentElement> getAllFragmentElements(final Fragment contextFragment) {
		return new Iterable<FragmentElement>() {
			
			public Iterator<FragmentElement> iterator() {
				return Iterators.filter(contextFragment.eAllContents(), FragmentElement.class);
			}
			
		};
	}

}
