/*
* generated by Xtext
*/
package org.eclipselabs.damos.dmltext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipselabs.damos.dmltext.services.DMLTextGrammarAccess;

public class DMLTextParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DMLTextGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipselabs.damos.dmltext.parser.antlr.internal.InternalDMLTextParser createParser(XtextTokenStream stream) {
		return new org.eclipselabs.damos.dmltext.parser.antlr.internal.InternalDMLTextParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Root";
	}
	
	public DMLTextGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DMLTextGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
