/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipselabs.damos.dml.edit.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;
import org.eclipselabs.damos.dml.util.DMLAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class DMLItemProviderAdapterFactory extends DMLAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public DMLItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.Fragment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FragmentItemProvider fragmentItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.Fragment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFragmentAdapter() {
		if (fragmentItemProvider == null) {
			fragmentItemProvider = new FragmentItemProvider(this);
		}

		return fragmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.ContinuousTimingConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContinuousTimingConstraintItemProvider continuousTimingConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.ContinuousTimingConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContinuousTimingConstraintAdapter() {
		if (continuousTimingConstraintItemProvider == null) {
			continuousTimingConstraintItemProvider = new ContinuousTimingConstraintItemProvider(this);
		}

		return continuousTimingConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.SynchronousTimingConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SynchronousTimingConstraintItemProvider synchronousTimingConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.SynchronousTimingConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSynchronousTimingConstraintAdapter() {
		if (synchronousTimingConstraintItemProvider == null) {
			synchronousTimingConstraintItemProvider = new SynchronousTimingConstraintItemProvider(this);
		}

		return synchronousTimingConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.AsynchronousTimingConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AsynchronousTimingConstraintItemProvider asynchronousTimingConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.AsynchronousTimingConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAsynchronousTimingConstraintAdapter() {
		if (asynchronousTimingConstraintItemProvider == null) {
			asynchronousTimingConstraintItemProvider = new AsynchronousTimingConstraintItemProvider(this);
		}

		return asynchronousTimingConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.Input} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InputItemProvider inputItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.Input}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInputAdapter() {
		if (inputItemProvider == null) {
			inputItemProvider = new InputItemProvider(this);
		}

		return inputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.InputPort} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InputPortItemProvider inputPortItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.InputPort}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInputPortAdapter() {
		if (inputPortItemProvider == null) {
			inputPortItemProvider = new InputPortItemProvider(this);
		}

		return inputPortItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.Connection} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConnectionItemProvider connectionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.Connection}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConnectionAdapter() {
		if (connectionItemProvider == null) {
			connectionItemProvider = new ConnectionItemProvider(this);
		}

		return connectionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.OutputPort} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OutputPortItemProvider outputPortItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.OutputPort}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOutputPortAdapter() {
		if (outputPortItemProvider == null) {
			outputPortItemProvider = new OutputPortItemProvider(this);
		}

		return outputPortItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.Output} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OutputItemProvider outputItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.Output}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOutputAdapter() {
		if (outputItemProvider == null) {
			outputItemProvider = new OutputItemProvider(this);
		}

		return outputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.BlockInput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BlockInputItemProvider blockInputItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.BlockInput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBlockInputAdapter() {
		if (blockInputItemProvider == null) {
			blockInputItemProvider = new BlockInputItemProvider(this);
		}

		return blockInputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.InputDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InputDefinitionItemProvider inputDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.InputDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInputDefinitionAdapter() {
		if (inputDefinitionItemProvider == null) {
			inputDefinitionItemProvider = new InputDefinitionItemProvider(this);
		}

		return inputDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.BlockOutput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BlockOutputItemProvider blockOutputItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.BlockOutput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBlockOutputAdapter() {
		if (blockOutputItemProvider == null) {
			blockOutputItemProvider = new BlockOutputItemProvider(this);
		}

		return blockOutputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.OutputDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OutputDefinitionItemProvider outputDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.OutputDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOutputDefinitionAdapter() {
		if (outputDefinitionItemProvider == null) {
			outputDefinitionItemProvider = new OutputDefinitionItemProvider(this);
		}

		return outputDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.Parameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParameterItemProvider parameterItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.Parameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParameterAdapter() {
		if (parameterItemProvider == null) {
			parameterItemProvider = new ParameterItemProvider(this);
		}

		return parameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.ParameterPredefinedValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParameterPredefinedValueItemProvider parameterPredefinedValueItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.ParameterPredefinedValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParameterPredefinedValueAdapter() {
		if (parameterPredefinedValueItemProvider == null) {
			parameterPredefinedValueItemProvider = new ParameterPredefinedValueItemProvider(this);
		}

		return parameterPredefinedValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.StringValueSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StringValueSpecificationItemProvider stringValueSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.StringValueSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStringValueSpecificationAdapter() {
		if (stringValueSpecificationItemProvider == null) {
			stringValueSpecificationItemProvider = new StringValueSpecificationItemProvider(this);
		}

		return stringValueSpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.PrimitiveTypeSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PrimitiveTypeSpecificationItemProvider primitiveTypeSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.PrimitiveTypeSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPrimitiveTypeSpecificationAdapter() {
		if (primitiveTypeSpecificationItemProvider == null) {
			primitiveTypeSpecificationItemProvider = new PrimitiveTypeSpecificationItemProvider(this);
		}

		return primitiveTypeSpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.Argument} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArgumentItemProvider argumentItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.Argument}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArgumentAdapter() {
		if (argumentItemProvider == null) {
			argumentItemProvider = new ArgumentItemProvider(this);
		}

		return argumentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.BlockType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BlockTypeItemProvider blockTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.BlockType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBlockTypeAdapter() {
		if (blockTypeItemProvider == null) {
			blockTypeItemProvider = new BlockTypeItemProvider(this);
		}

		return blockTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.Category} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CategoryItemProvider categoryItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.Category}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCategoryAdapter() {
		if (categoryItemProvider == null) {
			categoryItemProvider = new CategoryItemProvider(this);
		}

		return categoryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.Block} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BlockItemProvider blockItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.Block}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBlockAdapter() {
		if (blockItemProvider == null) {
			blockItemProvider = new BlockItemProvider(this);
		}

		return blockItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.Model} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModelItemProvider modelItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.Model}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModelAdapter() {
		if (modelItemProvider == null) {
			modelItemProvider = new ModelItemProvider(this);
		}

		return modelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.System} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SystemItemProvider systemItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.System}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSystemAdapter() {
		if (systemItemProvider == null) {
			systemItemProvider = new SystemItemProvider(this);
		}

		return systemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.BlockInputPort} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BlockInputPortItemProvider blockInputPortItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.BlockInputPort}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBlockInputPortAdapter() {
		if (blockInputPortItemProvider == null) {
			blockInputPortItemProvider = new BlockInputPortItemProvider(this);
		}

		return blockInputPortItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.BlockOutputPort} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BlockOutputPortItemProvider blockOutputPortItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.BlockOutputPort}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBlockOutputPortAdapter() {
		if (blockOutputPortItemProvider == null) {
			blockOutputPortItemProvider = new BlockOutputPortItemProvider(this);
		}

		return blockOutputPortItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.Subsystem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubsystemItemProvider subsystemItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.Subsystem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubsystemAdapter() {
		if (subsystemItemProvider == null) {
			subsystemItemProvider = new SubsystemItemProvider(this);
		}

		return subsystemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.SystemInterface} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SystemInterfaceItemProvider systemInterfaceItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.SystemInterface}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSystemInterfaceAdapter() {
		if (systemInterfaceItemProvider == null) {
			systemInterfaceItemProvider = new SystemInterfaceItemProvider(this);
		}

		return systemInterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.Inlet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InletItemProvider inletItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.Inlet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInletAdapter() {
		if (inletItemProvider == null) {
			inletItemProvider = new InletItemProvider(this);
		}

		return inletItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.Outlet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OutletItemProvider outletItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.Outlet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOutletAdapter() {
		if (outletItemProvider == null) {
			outletItemProvider = new OutletItemProvider(this);
		}

		return outletItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.SubsystemRealization} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubsystemRealizationItemProvider subsystemRealizationItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.SubsystemRealization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubsystemRealizationAdapter() {
		if (subsystemRealizationItemProvider == null) {
			subsystemRealizationItemProvider = new SubsystemRealizationItemProvider(this);
		}

		return subsystemRealizationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.Inport} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InportItemProvider inportItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.Inport}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInportAdapter() {
		if (inportItemProvider == null) {
			inportItemProvider = new InportItemProvider(this);
		}

		return inportItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.InportInput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InportInputItemProvider inportInputItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.InportInput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInportInputAdapter() {
		if (inportInputItemProvider == null) {
			inportInputItemProvider = new InportInputItemProvider(this);
		}

		return inportInputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.Outport} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OutportItemProvider outportItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.Outport}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOutportAdapter() {
		if (outportItemProvider == null) {
			outportItemProvider = new OutportItemProvider(this);
		}

		return outportItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.OutportOutput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OutportOutputItemProvider outportOutputItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.OutportOutput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOutportOutputAdapter() {
		if (outportOutputItemProvider == null) {
			outportOutputItemProvider = new OutportOutputItemProvider(this);
		}

		return outportOutputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.SubsystemInput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubsystemInputItemProvider subsystemInputItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.SubsystemInput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubsystemInputAdapter() {
		if (subsystemInputItemProvider == null) {
			subsystemInputItemProvider = new SubsystemInputItemProvider(this);
		}

		return subsystemInputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.SubsystemOutput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubsystemOutputItemProvider subsystemOutputItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.SubsystemOutput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubsystemOutputAdapter() {
		if (subsystemOutputItemProvider == null) {
			subsystemOutputItemProvider = new SubsystemOutputItemProvider(this);
		}

		return subsystemOutputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.BooleanDirectFeedthroughPolicy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BooleanDirectFeedthroughPolicyItemProvider booleanDirectFeedthroughPolicyItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.BooleanDirectFeedthroughPolicy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBooleanDirectFeedthroughPolicyAdapter() {
		if (booleanDirectFeedthroughPolicyItemProvider == null) {
			booleanDirectFeedthroughPolicyItemProvider = new BooleanDirectFeedthroughPolicyItemProvider(this);
		}

		return booleanDirectFeedthroughPolicyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.Latch} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LatchItemProvider latchItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.Latch}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLatchAdapter() {
		if (latchItemProvider == null) {
			latchItemProvider = new LatchItemProvider(this);
		}

		return latchItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.LatchInput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LatchInputItemProvider latchInputItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.LatchInput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLatchInputAdapter() {
		if (latchInputItemProvider == null) {
			latchInputItemProvider = new LatchInputItemProvider(this);
		}

		return latchInputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.Choice} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChoiceItemProvider choiceItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.Choice}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChoiceAdapter() {
		if (choiceItemProvider == null) {
			choiceItemProvider = new ChoiceItemProvider(this);
		}

		return choiceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.ChoiceInput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChoiceInputItemProvider choiceInputItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.ChoiceInput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChoiceInputAdapter() {
		if (choiceInputItemProvider == null) {
			choiceInputItemProvider = new ChoiceInputItemProvider(this);
		}

		return choiceInputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.ChoiceInputPort} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChoiceInputPortItemProvider choiceInputPortItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.ChoiceInputPort}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChoiceInputPortAdapter() {
		if (choiceInputPortItemProvider == null) {
			choiceInputPortItemProvider = new ChoiceInputPortItemProvider(this);
		}

		return choiceInputPortItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.Action} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActionItemProvider actionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.Action}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createActionAdapter() {
		if (actionItemProvider == null) {
			actionItemProvider = new ActionItemProvider(this);
		}

		return actionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.ActionLink} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActionLinkItemProvider actionLinkItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.ActionLink}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createActionLinkAdapter() {
		if (actionLinkItemProvider == null) {
			actionLinkItemProvider = new ActionLinkItemProvider(this);
		}

		return actionLinkItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.Join} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JoinItemProvider joinItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.Join}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJoinAdapter() {
		if (joinItemProvider == null) {
			joinItemProvider = new JoinItemProvider(this);
		}

		return joinItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.JoinInput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JoinInputItemProvider joinInputItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.JoinInput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJoinInputAdapter() {
		if (joinInputItemProvider == null) {
			joinInputItemProvider = new JoinInputItemProvider(this);
		}

		return joinInputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.WhileLoop} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WhileLoopItemProvider whileLoopItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.WhileLoop}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWhileLoopAdapter() {
		if (whileLoopItemProvider == null) {
			whileLoopItemProvider = new WhileLoopItemProvider(this);
		}

		return whileLoopItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.WhileLoopCondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WhileLoopConditionItemProvider whileLoopConditionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.WhileLoopCondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWhileLoopConditionAdapter() {
		if (whileLoopConditionItemProvider == null) {
			whileLoopConditionItemProvider = new WhileLoopConditionItemProvider(this);
		}

		return whileLoopConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.Memory} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MemoryItemProvider memoryItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.Memory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMemoryAdapter() {
		if (memoryItemProvider == null) {
			memoryItemProvider = new MemoryItemProvider(this);
		}

		return memoryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.MemoryInitialCondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MemoryInitialConditionItemProvider memoryInitialConditionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.MemoryInitialCondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMemoryInitialConditionAdapter() {
		if (memoryInitialConditionItemProvider == null) {
			memoryInitialConditionItemProvider = new MemoryInitialConditionItemProvider(this);
		}

		return memoryInitialConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.MemoryInput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MemoryInputItemProvider memoryInputItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.MemoryInput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMemoryInputAdapter() {
		if (memoryInputItemProvider == null) {
			memoryInputItemProvider = new MemoryInputItemProvider(this);
		}

		return memoryInputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipselabs.damos.dml.MemoryOutput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MemoryOutputItemProvider memoryOutputItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipselabs.damos.dml.MemoryOutput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMemoryOutputAdapter() {
		if (memoryOutputItemProvider == null) {
			memoryOutputItemProvider = new MemoryOutputItemProvider(this);
		}

		return memoryOutputItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (fragmentItemProvider != null) fragmentItemProvider.dispose();
		if (continuousTimingConstraintItemProvider != null) continuousTimingConstraintItemProvider.dispose();
		if (synchronousTimingConstraintItemProvider != null) synchronousTimingConstraintItemProvider.dispose();
		if (asynchronousTimingConstraintItemProvider != null) asynchronousTimingConstraintItemProvider.dispose();
		if (connectionItemProvider != null) connectionItemProvider.dispose();
		if (inputItemProvider != null) inputItemProvider.dispose();
		if (outputItemProvider != null) outputItemProvider.dispose();
		if (inputPortItemProvider != null) inputPortItemProvider.dispose();
		if (outputPortItemProvider != null) outputPortItemProvider.dispose();
		if (blockInputItemProvider != null) blockInputItemProvider.dispose();
		if (blockOutputItemProvider != null) blockOutputItemProvider.dispose();
		if (inputDefinitionItemProvider != null) inputDefinitionItemProvider.dispose();
		if (outputDefinitionItemProvider != null) outputDefinitionItemProvider.dispose();
		if (parameterItemProvider != null) parameterItemProvider.dispose();
		if (parameterPredefinedValueItemProvider != null) parameterPredefinedValueItemProvider.dispose();
		if (stringValueSpecificationItemProvider != null) stringValueSpecificationItemProvider.dispose();
		if (primitiveTypeSpecificationItemProvider != null) primitiveTypeSpecificationItemProvider.dispose();
		if (argumentItemProvider != null) argumentItemProvider.dispose();
		if (blockTypeItemProvider != null) blockTypeItemProvider.dispose();
		if (categoryItemProvider != null) categoryItemProvider.dispose();
		if (blockItemProvider != null) blockItemProvider.dispose();
		if (modelItemProvider != null) modelItemProvider.dispose();
		if (systemItemProvider != null) systemItemProvider.dispose();
		if (blockInputPortItemProvider != null) blockInputPortItemProvider.dispose();
		if (blockOutputPortItemProvider != null) blockOutputPortItemProvider.dispose();
		if (subsystemItemProvider != null) subsystemItemProvider.dispose();
		if (systemInterfaceItemProvider != null) systemInterfaceItemProvider.dispose();
		if (inletItemProvider != null) inletItemProvider.dispose();
		if (outletItemProvider != null) outletItemProvider.dispose();
		if (subsystemRealizationItemProvider != null) subsystemRealizationItemProvider.dispose();
		if (inportItemProvider != null) inportItemProvider.dispose();
		if (inportInputItemProvider != null) inportInputItemProvider.dispose();
		if (outportItemProvider != null) outportItemProvider.dispose();
		if (outportOutputItemProvider != null) outportOutputItemProvider.dispose();
		if (subsystemInputItemProvider != null) subsystemInputItemProvider.dispose();
		if (subsystemOutputItemProvider != null) subsystemOutputItemProvider.dispose();
		if (booleanDirectFeedthroughPolicyItemProvider != null) booleanDirectFeedthroughPolicyItemProvider.dispose();
		if (latchItemProvider != null) latchItemProvider.dispose();
		if (latchInputItemProvider != null) latchInputItemProvider.dispose();
		if (choiceItemProvider != null) choiceItemProvider.dispose();
		if (choiceInputItemProvider != null) choiceInputItemProvider.dispose();
		if (choiceInputPortItemProvider != null) choiceInputPortItemProvider.dispose();
		if (actionItemProvider != null) actionItemProvider.dispose();
		if (actionLinkItemProvider != null) actionLinkItemProvider.dispose();
		if (joinItemProvider != null) joinItemProvider.dispose();
		if (joinInputItemProvider != null) joinInputItemProvider.dispose();
		if (whileLoopItemProvider != null) whileLoopItemProvider.dispose();
		if (whileLoopConditionItemProvider != null) whileLoopConditionItemProvider.dispose();
		if (memoryItemProvider != null) memoryItemProvider.dispose();
		if (memoryInitialConditionItemProvider != null) memoryInitialConditionItemProvider.dispose();
		if (memoryInputItemProvider != null) memoryInputItemProvider.dispose();
		if (memoryOutputItemProvider != null) memoryOutputItemProvider.dispose();
	}

}
