/*
* generated by Xtext
*/
package org.eclipselabs.damos.dconfig.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipselabs.damos.dconfig.services.DconfigGrammarAccess;

public class DconfigParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DconfigGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipselabs.damos.dconfig.parser.antlr.internal.InternalDconfigParser createParser(XtextTokenStream stream) {
		return new org.eclipselabs.damos.dconfig.parser.antlr.internal.InternalDconfigParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Configuration";
	}
	
	public DconfigGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DconfigGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
