/*
* generated by Xtext
*/
package org.eclipselabs.damos.dmltext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DMLTextUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.eclipselabs.damos.dmltext.ui.internal.DMLTextActivator.getInstance().getInjector("org.eclipselabs.damos.dmltext.DMLText");
	}
	
}
