/*
* generated by Xtext
*/
package org.eclipselabs.damos.dscript.ui.contentassist;

import org.eclipselabs.damos.dscript.ui.contentassist.AbstractDscriptProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class DscriptProposalProvider extends AbstractDscriptProposalProvider {

}
