/*
* generated by Xtext
*/

package org.eclipselabs.damos.mscript.computationmodel.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipselabs.damos.mscript.services.MscriptGrammarAccess;

@Singleton
public class ComputationModelGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ComputationModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ComputationModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cComputationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cQualifiedNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cQualifiedNameQualifiedNameParserRuleCall_1_0 = (RuleCall)cQualifiedNameAssignment_1.eContents().get(0);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final Assignment cNumberFormatsAssignment_2_0 = (Assignment)cAlternatives_2.eContents().get(0);
		private final RuleCall cNumberFormatsNumberFormatParserRuleCall_2_0_0 = (RuleCall)cNumberFormatsAssignment_2_0.eContents().get(0);
		private final Assignment cNumberFormatMappingsAssignment_2_1 = (Assignment)cAlternatives_2.eContents().get(1);
		private final RuleCall cNumberFormatMappingsNumberFormatMappingParserRuleCall_2_1_0 = (RuleCall)cNumberFormatMappingsAssignment_2_1.eContents().get(0);
		
		//ComputationModel:
		//	"computation" qualifiedName=QualifiedName (numberFormats+=NumberFormat | numberFormatMappings+=NumberFormatMapping)*;
		public ParserRule getRule() { return rule; }

		//"computation" qualifiedName=QualifiedName (numberFormats+=NumberFormat | numberFormatMappings+=NumberFormatMapping)*
		public Group getGroup() { return cGroup; }

		//"computation"
		public Keyword getComputationKeyword_0() { return cComputationKeyword_0; }

		//qualifiedName=QualifiedName
		public Assignment getQualifiedNameAssignment_1() { return cQualifiedNameAssignment_1; }

		//QualifiedName
		public RuleCall getQualifiedNameQualifiedNameParserRuleCall_1_0() { return cQualifiedNameQualifiedNameParserRuleCall_1_0; }

		//(numberFormats+=NumberFormat | numberFormatMappings+=NumberFormatMapping)*
		public Alternatives getAlternatives_2() { return cAlternatives_2; }

		//numberFormats+=NumberFormat
		public Assignment getNumberFormatsAssignment_2_0() { return cNumberFormatsAssignment_2_0; }

		//NumberFormat
		public RuleCall getNumberFormatsNumberFormatParserRuleCall_2_0_0() { return cNumberFormatsNumberFormatParserRuleCall_2_0_0; }

		//numberFormatMappings+=NumberFormatMapping
		public Assignment getNumberFormatMappingsAssignment_2_1() { return cNumberFormatMappingsAssignment_2_1; }

		//NumberFormatMapping
		public RuleCall getNumberFormatMappingsNumberFormatMappingParserRuleCall_2_1_0() { return cNumberFormatMappingsNumberFormatMappingParserRuleCall_2_1_0; }
	}

	public class NumberFormatElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "NumberFormat");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cFloatingPointFormatParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cFixedPointFormatParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//NumberFormat:
		//	FloatingPointFormat | FixedPointFormat;
		public ParserRule getRule() { return rule; }

		//FloatingPointFormat | FixedPointFormat
		public Alternatives getAlternatives() { return cAlternatives; }

		//FloatingPointFormat
		public RuleCall getFloatingPointFormatParserRuleCall_0() { return cFloatingPointFormatParserRuleCall_0; }

		//FixedPointFormat
		public RuleCall getFixedPointFormatParserRuleCall_1() { return cFixedPointFormatParserRuleCall_1; }
	}

	public class FloatingPointFormatElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FloatingPointFormat");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFloatKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cKindAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cKindFloatingPointFormatKindEnumRuleCall_1_0 = (RuleCall)cKindAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameValidIDParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//FloatingPointFormat:
		//	"float" kind=FloatingPointFormatKind name=ValidID?;
		public ParserRule getRule() { return rule; }

		//"float" kind=FloatingPointFormatKind name=ValidID?
		public Group getGroup() { return cGroup; }

		//"float"
		public Keyword getFloatKeyword_0() { return cFloatKeyword_0; }

		//kind=FloatingPointFormatKind
		public Assignment getKindAssignment_1() { return cKindAssignment_1; }

		//FloatingPointFormatKind
		public RuleCall getKindFloatingPointFormatKindEnumRuleCall_1_0() { return cKindFloatingPointFormatKindEnumRuleCall_1_0; }

		//name=ValidID?
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ValidID
		public RuleCall getNameValidIDParserRuleCall_2_0() { return cNameValidIDParserRuleCall_2_0; }
	}

	public class FixedPointFormatElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FixedPointFormat");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Group cGroup_0_0 = (Group)cAlternatives_0.eContents().get(0);
		private final Keyword cFixKeyword_0_0_0 = (Keyword)cGroup_0_0.eContents().get(0);
		private final Assignment cIntegerLengthAssignment_0_0_1 = (Assignment)cGroup_0_0.eContents().get(1);
		private final RuleCall cIntegerLengthValidIntParserRuleCall_0_0_1_0 = (RuleCall)cIntegerLengthAssignment_0_0_1.eContents().get(0);
		private final Group cGroup_0_0_2 = (Group)cGroup_0_0.eContents().get(2);
		private final Keyword cFullStopKeyword_0_0_2_0 = (Keyword)cGroup_0_0_2.eContents().get(0);
		private final Assignment cFractionLengthAssignment_0_0_2_1 = (Assignment)cGroup_0_0_2.eContents().get(1);
		private final RuleCall cFractionLengthValidIntParserRuleCall_0_0_2_1_0 = (RuleCall)cFractionLengthAssignment_0_0_2_1.eContents().get(0);
		private final Group cGroup_0_1 = (Group)cAlternatives_0.eContents().get(1);
		private final Keyword cFractKeyword_0_1_0 = (Keyword)cGroup_0_1.eContents().get(0);
		private final Assignment cFractionLengthAssignment_0_1_1 = (Assignment)cGroup_0_1.eContents().get(1);
		private final RuleCall cFractionLengthFractionLiteralParserRuleCall_0_1_1_0 = (RuleCall)cFractionLengthAssignment_0_1_1.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameValidIDParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cOperationsAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cOperationsFixedPointOperationParserRuleCall_2_1_0 = (RuleCall)cOperationsAssignment_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		
		//FixedPointFormat:
		//	("fix" integerLength=ValidInt ("." fractionLength=ValidInt)? | "fract" fractionLength=FractionLiteral) name=ValidID?
		//	("{" operations+=FixedPointOperation+ "}")?;
		public ParserRule getRule() { return rule; }

		//("fix" integerLength=ValidInt ("." fractionLength=ValidInt)? | "fract" fractionLength=FractionLiteral) name=ValidID?
		//("{" operations+=FixedPointOperation+ "}")?
		public Group getGroup() { return cGroup; }

		//"fix" integerLength=ValidInt ("." fractionLength=ValidInt)? | "fract" fractionLength=FractionLiteral
		public Alternatives getAlternatives_0() { return cAlternatives_0; }

		//"fix" integerLength=ValidInt ("." fractionLength=ValidInt)?
		public Group getGroup_0_0() { return cGroup_0_0; }

		//"fix"
		public Keyword getFixKeyword_0_0_0() { return cFixKeyword_0_0_0; }

		//integerLength=ValidInt
		public Assignment getIntegerLengthAssignment_0_0_1() { return cIntegerLengthAssignment_0_0_1; }

		//ValidInt
		public RuleCall getIntegerLengthValidIntParserRuleCall_0_0_1_0() { return cIntegerLengthValidIntParserRuleCall_0_0_1_0; }

		//("." fractionLength=ValidInt)?
		public Group getGroup_0_0_2() { return cGroup_0_0_2; }

		//"."
		public Keyword getFullStopKeyword_0_0_2_0() { return cFullStopKeyword_0_0_2_0; }

		//fractionLength=ValidInt
		public Assignment getFractionLengthAssignment_0_0_2_1() { return cFractionLengthAssignment_0_0_2_1; }

		//ValidInt
		public RuleCall getFractionLengthValidIntParserRuleCall_0_0_2_1_0() { return cFractionLengthValidIntParserRuleCall_0_0_2_1_0; }

		//"fract" fractionLength=FractionLiteral
		public Group getGroup_0_1() { return cGroup_0_1; }

		//"fract"
		public Keyword getFractKeyword_0_1_0() { return cFractKeyword_0_1_0; }

		//fractionLength=FractionLiteral
		public Assignment getFractionLengthAssignment_0_1_1() { return cFractionLengthAssignment_0_1_1; }

		//FractionLiteral
		public RuleCall getFractionLengthFractionLiteralParserRuleCall_0_1_1_0() { return cFractionLengthFractionLiteralParserRuleCall_0_1_1_0; }

		//name=ValidID?
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ValidID
		public RuleCall getNameValidIDParserRuleCall_1_0() { return cNameValidIDParserRuleCall_1_0; }

		//("{" operations+=FixedPointOperation+ "}")?
		public Group getGroup_2() { return cGroup_2; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2_0() { return cLeftCurlyBracketKeyword_2_0; }

		//operations+=FixedPointOperation+
		public Assignment getOperationsAssignment_2_1() { return cOperationsAssignment_2_1; }

		//FixedPointOperation
		public RuleCall getOperationsFixedPointOperationParserRuleCall_2_1_0() { return cOperationsFixedPointOperationParserRuleCall_2_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_2_2() { return cRightCurlyBracketKeyword_2_2; }
	}

	public class FixedPointOperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FixedPointOperation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cKindAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cKindFixedPointOperationKindEnumRuleCall_0_0 = (RuleCall)cKindAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final UnorderedGroup cUnorderedGroup_2 = (UnorderedGroup)cGroup.eContents().get(2);
		private final Group cGroup_2_0 = (Group)cUnorderedGroup_2.eContents().get(0);
		private final Keyword cIntermediateKeyword_2_0_0 = (Keyword)cGroup_2_0.eContents().get(0);
		private final Assignment cIntermediateWordSizeAssignment_2_0_1 = (Assignment)cGroup_2_0.eContents().get(1);
		private final RuleCall cIntermediateWordSizeValidIntParserRuleCall_2_0_1_0 = (RuleCall)cIntermediateWordSizeAssignment_2_0_1.eContents().get(0);
		private final Assignment cSaturateAssignment_2_1 = (Assignment)cUnorderedGroup_2.eContents().get(1);
		private final Keyword cSaturateSaturateKeyword_2_1_0 = (Keyword)cSaturateAssignment_2_1.eContents().get(0);
		
		//FixedPointOperation:
		//	kind=FixedPointOperationKind ":" ("intermediate" intermediateWordSize=ValidInt & saturate?="saturate"?);
		public ParserRule getRule() { return rule; }

		//kind=FixedPointOperationKind ":" ("intermediate" intermediateWordSize=ValidInt & saturate?="saturate"?)
		public Group getGroup() { return cGroup; }

		//kind=FixedPointOperationKind
		public Assignment getKindAssignment_0() { return cKindAssignment_0; }

		//FixedPointOperationKind
		public RuleCall getKindFixedPointOperationKindEnumRuleCall_0_0() { return cKindFixedPointOperationKindEnumRuleCall_0_0; }

		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }

		//"intermediate" intermediateWordSize=ValidInt & saturate?="saturate"?
		public UnorderedGroup getUnorderedGroup_2() { return cUnorderedGroup_2; }

		//"intermediate" intermediateWordSize=ValidInt
		public Group getGroup_2_0() { return cGroup_2_0; }

		//"intermediate"
		public Keyword getIntermediateKeyword_2_0_0() { return cIntermediateKeyword_2_0_0; }

		//intermediateWordSize=ValidInt
		public Assignment getIntermediateWordSizeAssignment_2_0_1() { return cIntermediateWordSizeAssignment_2_0_1; }

		//ValidInt
		public RuleCall getIntermediateWordSizeValidIntParserRuleCall_2_0_1_0() { return cIntermediateWordSizeValidIntParserRuleCall_2_0_1_0; }

		//saturate?="saturate"?
		public Assignment getSaturateAssignment_2_1() { return cSaturateAssignment_2_1; }

		//"saturate"
		public Keyword getSaturateSaturateKeyword_2_1_0() { return cSaturateSaturateKeyword_2_1_0; }
	}

	public class FractionLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FractionLiteral");
		private final RuleCall cValidIntParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//FractionLiteral returns ecore::EInt:
		//	ValidInt;
		public ParserRule getRule() { return rule; }

		//ValidInt
		public RuleCall getValidIntParserRuleCall() { return cValidIntParserRuleCall; }
	}

	public class NumberFormatMappingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "NumberFormatMapping");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMapKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTypeSpecifierAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeSpecifierDataTypeSpecifierParserRuleCall_1_0 = (RuleCall)cTypeSpecifierAssignment_1.eContents().get(0);
		private final Keyword cToKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNumberFormatAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cNumberFormatNumberFormatCrossReference_3_0 = (CrossReference)cNumberFormatAssignment_3.eContents().get(0);
		private final RuleCall cNumberFormatNumberFormatIDTerminalRuleCall_3_0_1 = (RuleCall)cNumberFormatNumberFormatCrossReference_3_0.eContents().get(1);
		
		//NumberFormatMapping:
		//	"map" typeSpecifier=DataTypeSpecifier "to" numberFormat=[NumberFormat];
		public ParserRule getRule() { return rule; }

		//"map" typeSpecifier=DataTypeSpecifier "to" numberFormat=[NumberFormat]
		public Group getGroup() { return cGroup; }

		//"map"
		public Keyword getMapKeyword_0() { return cMapKeyword_0; }

		//typeSpecifier=DataTypeSpecifier
		public Assignment getTypeSpecifierAssignment_1() { return cTypeSpecifierAssignment_1; }

		//DataTypeSpecifier
		public RuleCall getTypeSpecifierDataTypeSpecifierParserRuleCall_1_0() { return cTypeSpecifierDataTypeSpecifierParserRuleCall_1_0; }

		//"to"
		public Keyword getToKeyword_2() { return cToKeyword_2; }

		//numberFormat=[NumberFormat]
		public Assignment getNumberFormatAssignment_3() { return cNumberFormatAssignment_3; }

		//[NumberFormat]
		public CrossReference getNumberFormatNumberFormatCrossReference_3_0() { return cNumberFormatNumberFormatCrossReference_3_0; }

		//ID
		public RuleCall getNumberFormatNumberFormatIDTerminalRuleCall_3_0_1() { return cNumberFormatNumberFormatIDTerminalRuleCall_3_0_1; }
	}
	
	
	public class FloatingPointFormatKindElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "FloatingPointFormatKind");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cBinary16EnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cBinary16Binary16Keyword_0_0 = (Keyword)cBinary16EnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cBinary32EnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cBinary32Binary32Keyword_1_0 = (Keyword)cBinary32EnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cBinary64EnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cBinary64Binary64Keyword_2_0 = (Keyword)cBinary64EnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cBinary128EnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cBinary128Binary128Keyword_3_0 = (Keyword)cBinary128EnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cDecimal32EnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cDecimal32Decimal32Keyword_4_0 = (Keyword)cDecimal32EnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cDecimal64EnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cDecimal64Decimal64Keyword_5_0 = (Keyword)cDecimal64EnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cDecimal128EnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cDecimal128Decimal128Keyword_6_0 = (Keyword)cDecimal128EnumLiteralDeclaration_6.eContents().get(0);
		
		//enum FloatingPointFormatKind:
		//	Binary16="binary16" | Binary32="binary32" | Binary64="binary64" | Binary128="binary128" | Decimal32="decimal32" |
		//	Decimal64="decimal64" | Decimal128="decimal128";
		public EnumRule getRule() { return rule; }

		//Binary16="binary16" | Binary32="binary32" | Binary64="binary64" | Binary128="binary128" | Decimal32="decimal32" |
		//Decimal64="decimal64" | Decimal128="decimal128"
		public Alternatives getAlternatives() { return cAlternatives; }

		//Binary16="binary16"
		public EnumLiteralDeclaration getBinary16EnumLiteralDeclaration_0() { return cBinary16EnumLiteralDeclaration_0; }

		//"binary16"
		public Keyword getBinary16Binary16Keyword_0_0() { return cBinary16Binary16Keyword_0_0; }

		//Binary32="binary32"
		public EnumLiteralDeclaration getBinary32EnumLiteralDeclaration_1() { return cBinary32EnumLiteralDeclaration_1; }

		//"binary32"
		public Keyword getBinary32Binary32Keyword_1_0() { return cBinary32Binary32Keyword_1_0; }

		//Binary64="binary64"
		public EnumLiteralDeclaration getBinary64EnumLiteralDeclaration_2() { return cBinary64EnumLiteralDeclaration_2; }

		//"binary64"
		public Keyword getBinary64Binary64Keyword_2_0() { return cBinary64Binary64Keyword_2_0; }

		//Binary128="binary128"
		public EnumLiteralDeclaration getBinary128EnumLiteralDeclaration_3() { return cBinary128EnumLiteralDeclaration_3; }

		//"binary128"
		public Keyword getBinary128Binary128Keyword_3_0() { return cBinary128Binary128Keyword_3_0; }

		//Decimal32="decimal32"
		public EnumLiteralDeclaration getDecimal32EnumLiteralDeclaration_4() { return cDecimal32EnumLiteralDeclaration_4; }

		//"decimal32"
		public Keyword getDecimal32Decimal32Keyword_4_0() { return cDecimal32Decimal32Keyword_4_0; }

		//Decimal64="decimal64"
		public EnumLiteralDeclaration getDecimal64EnumLiteralDeclaration_5() { return cDecimal64EnumLiteralDeclaration_5; }

		//"decimal64"
		public Keyword getDecimal64Decimal64Keyword_5_0() { return cDecimal64Decimal64Keyword_5_0; }

		//Decimal128="decimal128"
		public EnumLiteralDeclaration getDecimal128EnumLiteralDeclaration_6() { return cDecimal128EnumLiteralDeclaration_6; }

		//"decimal128"
		public Keyword getDecimal128Decimal128Keyword_6_0() { return cDecimal128Decimal128Keyword_6_0; }
	}

	public class FixedPointOperationKindElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "FixedPointOperationKind");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cConstructEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cConstructConstructKeyword_0_0 = (Keyword)cConstructEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cCastEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cCastCastKeyword_1_0 = (Keyword)cCastEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cAddEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cAddAddKeyword_2_0 = (Keyword)cAddEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cSubtractEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cSubtractSubtractKeyword_3_0 = (Keyword)cSubtractEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cMultiplyEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cMultiplyMultiplyKeyword_4_0 = (Keyword)cMultiplyEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cDivideEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cDivideDivideKeyword_5_0 = (Keyword)cDivideEnumLiteralDeclaration_5.eContents().get(0);
		
		//enum FixedPointOperationKind:
		//	Construct="construct" | Cast="cast" | Add="add" | Subtract="subtract" | Multiply="multiply" | Divide="divide";
		public EnumRule getRule() { return rule; }

		//Construct="construct" | Cast="cast" | Add="add" | Subtract="subtract" | Multiply="multiply" | Divide="divide"
		public Alternatives getAlternatives() { return cAlternatives; }

		//Construct="construct"
		public EnumLiteralDeclaration getConstructEnumLiteralDeclaration_0() { return cConstructEnumLiteralDeclaration_0; }

		//"construct"
		public Keyword getConstructConstructKeyword_0_0() { return cConstructConstructKeyword_0_0; }

		//Cast="cast"
		public EnumLiteralDeclaration getCastEnumLiteralDeclaration_1() { return cCastEnumLiteralDeclaration_1; }

		//"cast"
		public Keyword getCastCastKeyword_1_0() { return cCastCastKeyword_1_0; }

		//Add="add"
		public EnumLiteralDeclaration getAddEnumLiteralDeclaration_2() { return cAddEnumLiteralDeclaration_2; }

		//"add"
		public Keyword getAddAddKeyword_2_0() { return cAddAddKeyword_2_0; }

		//Subtract="subtract"
		public EnumLiteralDeclaration getSubtractEnumLiteralDeclaration_3() { return cSubtractEnumLiteralDeclaration_3; }

		//"subtract"
		public Keyword getSubtractSubtractKeyword_3_0() { return cSubtractSubtractKeyword_3_0; }

		//Multiply="multiply"
		public EnumLiteralDeclaration getMultiplyEnumLiteralDeclaration_4() { return cMultiplyEnumLiteralDeclaration_4; }

		//"multiply"
		public Keyword getMultiplyMultiplyKeyword_4_0() { return cMultiplyMultiplyKeyword_4_0; }

		//Divide="divide"
		public EnumLiteralDeclaration getDivideEnumLiteralDeclaration_5() { return cDivideEnumLiteralDeclaration_5; }

		//"divide"
		public Keyword getDivideDivideKeyword_5_0() { return cDivideDivideKeyword_5_0; }
	}
	
	private ComputationModelElements pComputationModel;
	private NumberFormatElements pNumberFormat;
	private FloatingPointFormatElements pFloatingPointFormat;
	private FloatingPointFormatKindElements unknownRuleFloatingPointFormatKind;
	private FixedPointFormatElements pFixedPointFormat;
	private FixedPointOperationElements pFixedPointOperation;
	private FixedPointOperationKindElements unknownRuleFixedPointOperationKind;
	private FractionLiteralElements pFractionLiteral;
	private NumberFormatMappingElements pNumberFormatMapping;
	
	private final GrammarProvider grammarProvider;

	private MscriptGrammarAccess gaMscript;

	@Inject
	public ComputationModelGrammarAccess(GrammarProvider grammarProvider,
		MscriptGrammarAccess gaMscript) {
		this.grammarProvider = grammarProvider;
		this.gaMscript = gaMscript;
	}
	
	public Grammar getGrammar() {	
		return grammarProvider.getGrammar(this);
	}
	

	public MscriptGrammarAccess getMscriptGrammarAccess() {
		return gaMscript;
	}

	
	//ComputationModel:
	//	"computation" qualifiedName=QualifiedName (numberFormats+=NumberFormat | numberFormatMappings+=NumberFormatMapping)*;
	public ComputationModelElements getComputationModelAccess() {
		return (pComputationModel != null) ? pComputationModel : (pComputationModel = new ComputationModelElements());
	}
	
	public ParserRule getComputationModelRule() {
		return getComputationModelAccess().getRule();
	}

	//NumberFormat:
	//	FloatingPointFormat | FixedPointFormat;
	public NumberFormatElements getNumberFormatAccess() {
		return (pNumberFormat != null) ? pNumberFormat : (pNumberFormat = new NumberFormatElements());
	}
	
	public ParserRule getNumberFormatRule() {
		return getNumberFormatAccess().getRule();
	}

	//FloatingPointFormat:
	//	"float" kind=FloatingPointFormatKind name=ValidID?;
	public FloatingPointFormatElements getFloatingPointFormatAccess() {
		return (pFloatingPointFormat != null) ? pFloatingPointFormat : (pFloatingPointFormat = new FloatingPointFormatElements());
	}
	
	public ParserRule getFloatingPointFormatRule() {
		return getFloatingPointFormatAccess().getRule();
	}

	//enum FloatingPointFormatKind:
	//	Binary16="binary16" | Binary32="binary32" | Binary64="binary64" | Binary128="binary128" | Decimal32="decimal32" |
	//	Decimal64="decimal64" | Decimal128="decimal128";
	public FloatingPointFormatKindElements getFloatingPointFormatKindAccess() {
		return (unknownRuleFloatingPointFormatKind != null) ? unknownRuleFloatingPointFormatKind : (unknownRuleFloatingPointFormatKind = new FloatingPointFormatKindElements());
	}
	
	public EnumRule getFloatingPointFormatKindRule() {
		return getFloatingPointFormatKindAccess().getRule();
	}

	//FixedPointFormat:
	//	("fix" integerLength=ValidInt ("." fractionLength=ValidInt)? | "fract" fractionLength=FractionLiteral) name=ValidID?
	//	("{" operations+=FixedPointOperation+ "}")?;
	public FixedPointFormatElements getFixedPointFormatAccess() {
		return (pFixedPointFormat != null) ? pFixedPointFormat : (pFixedPointFormat = new FixedPointFormatElements());
	}
	
	public ParserRule getFixedPointFormatRule() {
		return getFixedPointFormatAccess().getRule();
	}

	//FixedPointOperation:
	//	kind=FixedPointOperationKind ":" ("intermediate" intermediateWordSize=ValidInt & saturate?="saturate"?);
	public FixedPointOperationElements getFixedPointOperationAccess() {
		return (pFixedPointOperation != null) ? pFixedPointOperation : (pFixedPointOperation = new FixedPointOperationElements());
	}
	
	public ParserRule getFixedPointOperationRule() {
		return getFixedPointOperationAccess().getRule();
	}

	//enum FixedPointOperationKind:
	//	Construct="construct" | Cast="cast" | Add="add" | Subtract="subtract" | Multiply="multiply" | Divide="divide";
	public FixedPointOperationKindElements getFixedPointOperationKindAccess() {
		return (unknownRuleFixedPointOperationKind != null) ? unknownRuleFixedPointOperationKind : (unknownRuleFixedPointOperationKind = new FixedPointOperationKindElements());
	}
	
	public EnumRule getFixedPointOperationKindRule() {
		return getFixedPointOperationKindAccess().getRule();
	}

	//FractionLiteral returns ecore::EInt:
	//	ValidInt;
	public FractionLiteralElements getFractionLiteralAccess() {
		return (pFractionLiteral != null) ? pFractionLiteral : (pFractionLiteral = new FractionLiteralElements());
	}
	
	public ParserRule getFractionLiteralRule() {
		return getFractionLiteralAccess().getRule();
	}

	//NumberFormatMapping:
	//	"map" typeSpecifier=DataTypeSpecifier "to" numberFormat=[NumberFormat];
	public NumberFormatMappingElements getNumberFormatMappingAccess() {
		return (pNumberFormatMapping != null) ? pNumberFormatMapping : (pNumberFormatMapping = new NumberFormatMappingElements());
	}
	
	public ParserRule getNumberFormatMappingRule() {
		return getNumberFormatMappingAccess().getRule();
	}

	//Module:
	//	definitions+=Definition*;
	public MscriptGrammarAccess.ModuleElements getModuleAccess() {
		return gaMscript.getModuleAccess();
	}
	
	public ParserRule getModuleRule() {
		return getModuleAccess().getRule();
	}

	//Definition:
	//	DataTypeDefinition | FunctionDefinition;
	public MscriptGrammarAccess.DefinitionElements getDefinitionAccess() {
		return gaMscript.getDefinitionAccess();
	}
	
	public ParserRule getDefinitionRule() {
		return getDefinitionAccess().getRule();
	}

	/// *
	// * DataTypeDefinition
	// * / DataTypeDefinition:
	//	EnumerationDefinition | StructDefinition | TypedefDeclaration;
	public MscriptGrammarAccess.DataTypeDefinitionElements getDataTypeDefinitionAccess() {
		return gaMscript.getDataTypeDefinitionAccess();
	}
	
	public ParserRule getDataTypeDefinitionRule() {
		return getDataTypeDefinitionAccess().getRule();
	}

	/// *
	// * Enumeration
	// * / EnumerationDefinition:
	//	"enum" name=ValidID "{" (literalDeclarations+=EnumerationLiteralDeclaration (","
	//	literalDeclarations+=EnumerationLiteralDeclaration)*)? "}";
	public MscriptGrammarAccess.EnumerationDefinitionElements getEnumerationDefinitionAccess() {
		return gaMscript.getEnumerationDefinitionAccess();
	}
	
	public ParserRule getEnumerationDefinitionRule() {
		return getEnumerationDefinitionAccess().getRule();
	}

	//EnumerationLiteralDeclaration:
	//	name=ValidID;
	public MscriptGrammarAccess.EnumerationLiteralDeclarationElements getEnumerationLiteralDeclarationAccess() {
		return gaMscript.getEnumerationLiteralDeclarationAccess();
	}
	
	public ParserRule getEnumerationLiteralDeclarationRule() {
		return getEnumerationLiteralDeclarationAccess().getRule();
	}

	/// *
	// * Typedef
	// * / TypedefDeclaration:
	//	"typedef" typeSpecifier=DataTypeSpecifier name=ValidID;
	public MscriptGrammarAccess.TypedefDeclarationElements getTypedefDeclarationAccess() {
		return gaMscript.getTypedefDeclarationAccess();
	}
	
	public ParserRule getTypedefDeclarationRule() {
		return getTypedefDeclarationAccess().getRule();
	}

	/// *
	// * Struct
	// * / StructDefinition:
	//	"struct" name=ValidID "{" memberDeclarations+=StructMemberDeclaration* "}";
	public MscriptGrammarAccess.StructDefinitionElements getStructDefinitionAccess() {
		return gaMscript.getStructDefinitionAccess();
	}
	
	public ParserRule getStructDefinitionRule() {
		return getStructDefinitionAccess().getRule();
	}

	//StructMemberDeclaration:
	//	typeSpecifier=DataTypeSpecifier name=ValidID;
	public MscriptGrammarAccess.StructMemberDeclarationElements getStructMemberDeclarationAccess() {
		return gaMscript.getStructMemberDeclarationAccess();
	}
	
	public ParserRule getStructMemberDeclarationRule() {
		return getStructMemberDeclarationAccess().getRule();
	}

	/// *
	// * Function
	// * / FunctionDefinition:
	//	kind=FunctionKind? "func" name=ValidID ("<" templateParameterDeclarations+=TemplateParameterDeclaration (","
	//	templateParameterDeclarations+=TemplateParameterDeclaration)* ">")? "("
	//	(inputParameterDeclarations+=InputParameterDeclaration ("," inputParameterDeclarations+=InputParameterDeclaration)*)?
	//	")" "->" outputParameterDeclarations+=OutputParameterDeclaration (","
	//	outputParameterDeclarations+=OutputParameterDeclaration)* "{" (checks+=Check | assertions+=Assertion |
	//	functionObjectDeclarations+=FunctionObjectDeclaration | stateVariableDeclarations+=StateVariableDeclaration |
	//	constantDeclarations+=ConstantDeclaration | equations+=Equation)* "}";
	public MscriptGrammarAccess.FunctionDefinitionElements getFunctionDefinitionAccess() {
		return gaMscript.getFunctionDefinitionAccess();
	}
	
	public ParserRule getFunctionDefinitionRule() {
		return getFunctionDefinitionAccess().getRule();
	}

	//enum FunctionKind:
	//	Stateful="stateful" | Continuous="continuous";
	public MscriptGrammarAccess.FunctionKindElements getFunctionKindAccess() {
		return gaMscript.getFunctionKindAccess();
	}
	
	public EnumRule getFunctionKindRule() {
		return getFunctionKindAccess().getRule();
	}

	//TemplateParameterDeclaration:
	//	name=ValidID;
	public MscriptGrammarAccess.TemplateParameterDeclarationElements getTemplateParameterDeclarationAccess() {
		return gaMscript.getTemplateParameterDeclarationAccess();
	}
	
	public ParserRule getTemplateParameterDeclarationRule() {
		return getTemplateParameterDeclarationAccess().getRule();
	}

	//InputParameterDeclaration:
	//	name=ValidID;
	public MscriptGrammarAccess.InputParameterDeclarationElements getInputParameterDeclarationAccess() {
		return gaMscript.getInputParameterDeclarationAccess();
	}
	
	public ParserRule getInputParameterDeclarationRule() {
		return getInputParameterDeclarationAccess().getRule();
	}

	//OutputParameterDeclaration:
	//	name=ValidID;
	public MscriptGrammarAccess.OutputParameterDeclarationElements getOutputParameterDeclarationAccess() {
		return gaMscript.getOutputParameterDeclarationAccess();
	}
	
	public ParserRule getOutputParameterDeclarationRule() {
		return getOutputParameterDeclarationAccess().getRule();
	}

	//Check:
	//	"check" ("<" templateArguments+=Expression ("," templateArguments+=Expression)* ">")? "("
	//	(inputParameterTypes+=DataTypeSpecifier ("," inputParameterTypes+=DataTypeSpecifier)*)? ")" "->"
	//	outputParameterTypes+=DataTypeSpecifier ("," outputParameterTypes+=DataTypeSpecifier)*;
	public MscriptGrammarAccess.CheckElements getCheckAccess() {
		return gaMscript.getCheckAccess();
	}
	
	public ParserRule getCheckRule() {
		return getCheckAccess().getRule();
	}

	//enum AssertionStatusKind:
	//	Info="info" | Warning="warning" | Error="error" | Fatal="fatal";
	public MscriptGrammarAccess.AssertionStatusKindElements getAssertionStatusKindAccess() {
		return gaMscript.getAssertionStatusKindAccess();
	}
	
	public EnumRule getAssertionStatusKindRule() {
		return getAssertionStatusKindAccess().getRule();
	}

	//Assertion:
	//	static?="static"? "assert" condition=Expression ":" statusKind=AssertionStatusKind message=Expression;
	public MscriptGrammarAccess.AssertionElements getAssertionAccess() {
		return gaMscript.getAssertionAccess();
	}
	
	public ParserRule getAssertionRule() {
		return getAssertionAccess().getRule();
	}

	//StateVariableDeclaration:
	//	"var" name=ValidID;
	public MscriptGrammarAccess.StateVariableDeclarationElements getStateVariableDeclarationAccess() {
		return gaMscript.getStateVariableDeclarationAccess();
	}
	
	public ParserRule getStateVariableDeclarationRule() {
		return getStateVariableDeclarationAccess().getRule();
	}

	//ConstantDeclaration:
	//	"const" name=ValidID "=" initializer=Expression;
	public MscriptGrammarAccess.ConstantDeclarationElements getConstantDeclarationAccess() {
		return gaMscript.getConstantDeclarationAccess();
	}
	
	public ParserRule getConstantDeclarationRule() {
		return getConstantDeclarationAccess().getRule();
	}

	//FunctionObjectDeclaration:
	//	"fob" functionName=[FunctionDefinition|QualifiedName] ("<" templateArguments+=Expression (","
	//	templateArguments+=Expression)* ">")? name=ValidID;
	public MscriptGrammarAccess.FunctionObjectDeclarationElements getFunctionObjectDeclarationAccess() {
		return gaMscript.getFunctionObjectDeclarationAccess();
	}
	
	public ParserRule getFunctionObjectDeclarationRule() {
		return getFunctionObjectDeclarationAccess().getRule();
	}

	//Equation:
	//	initial?="initial"? "eq" leftHandSide=Expression "=" rightHandSide=Expression;
	public MscriptGrammarAccess.EquationElements getEquationAccess() {
		return gaMscript.getEquationAccess();
	}
	
	public ParserRule getEquationRule() {
		return getEquationAccess().getRule();
	}

	/// *
	// * Data type specifier
	// * / DataTypeSpecifier:
	//	definedType=(PrimitiveType | ArrayType) | type=[DataType|QualifiedName];
	public MscriptGrammarAccess.DataTypeSpecifierElements getDataTypeSpecifierAccess() {
		return gaMscript.getDataTypeSpecifierAccess();
	}
	
	public ParserRule getDataTypeSpecifierRule() {
		return getDataTypeSpecifierAccess().getRule();
	}

	//PrimitiveType:
	//	NumericType | BooleanType | StringType;
	public MscriptGrammarAccess.PrimitiveTypeElements getPrimitiveTypeAccess() {
		return gaMscript.getPrimitiveTypeAccess();
	}
	
	public ParserRule getPrimitiveTypeRule() {
		return getPrimitiveTypeAccess().getRule();
	}

	//NumericType:
	//	RealType | IntegerType | ComplexType | GaussianType;
	public MscriptGrammarAccess.NumericTypeElements getNumericTypeAccess() {
		return gaMscript.getNumericTypeAccess();
	}
	
	public ParserRule getNumericTypeRule() {
		return getNumericTypeAccess().getRule();
	}

	//RealType:
	//	{RealType} "real" unit=Unit;
	public MscriptGrammarAccess.RealTypeElements getRealTypeAccess() {
		return gaMscript.getRealTypeAccess();
	}
	
	public ParserRule getRealTypeRule() {
		return getRealTypeAccess().getRule();
	}

	//IntegerType:
	//	{IntegerType} "int" unit=Unit;
	public MscriptGrammarAccess.IntegerTypeElements getIntegerTypeAccess() {
		return gaMscript.getIntegerTypeAccess();
	}
	
	public ParserRule getIntegerTypeRule() {
		return getIntegerTypeAccess().getRule();
	}

	//ComplexType:
	//	{ComplexType} "complex" unit=Unit;
	public MscriptGrammarAccess.ComplexTypeElements getComplexTypeAccess() {
		return gaMscript.getComplexTypeAccess();
	}
	
	public ParserRule getComplexTypeRule() {
		return getComplexTypeAccess().getRule();
	}

	//GaussianType:
	//	{GaussianType} "gauss" unit=Unit;
	public MscriptGrammarAccess.GaussianTypeElements getGaussianTypeAccess() {
		return gaMscript.getGaussianTypeAccess();
	}
	
	public ParserRule getGaussianTypeRule() {
		return getGaussianTypeAccess().getRule();
	}

	//BooleanType:
	//	{BooleanType} "bool";
	public MscriptGrammarAccess.BooleanTypeElements getBooleanTypeAccess() {
		return gaMscript.getBooleanTypeAccess();
	}
	
	public ParserRule getBooleanTypeRule() {
		return getBooleanTypeAccess().getRule();
	}

	//StringType:
	//	{StringType} "string";
	public MscriptGrammarAccess.StringTypeElements getStringTypeAccess() {
		return gaMscript.getStringTypeAccess();
	}
	
	public ParserRule getStringTypeRule() {
		return getStringTypeAccess().getRule();
	}

	//ArrayType:
	//	TensorType | => (definedElementType=(BooleanType | StringType) | elementType=[DataType]) "["
	//	dimensions+=ArrayDimension ("," dimensions+=ArrayDimension)* "]";
	public MscriptGrammarAccess.ArrayTypeElements getArrayTypeAccess() {
		return gaMscript.getArrayTypeAccess();
	}
	
	public ParserRule getArrayTypeRule() {
		return getArrayTypeAccess().getRule();
	}

	//TensorType:
	//	definedElementType=NumericType "[" dimensions+=ArrayDimension ("," dimensions+=ArrayDimension)* "]";
	public MscriptGrammarAccess.TensorTypeElements getTensorTypeAccess() {
		return gaMscript.getTensorTypeAccess();
	}
	
	public ParserRule getTensorTypeRule() {
		return getTensorTypeAccess().getRule();
	}

	//ArrayDimension:
	//	{ArrayDimension} size=Expression?;
	public MscriptGrammarAccess.ArrayDimensionElements getArrayDimensionAccess() {
		return gaMscript.getArrayDimensionAccess();
	}
	
	public ParserRule getArrayDimensionRule() {
		return getArrayDimensionAccess().getRule();
	}

	/// *
	// * Expressions
	// * / Expression:
	//	LetExpression | IfExpression | SwitchExpression | RangeExpression;
	public MscriptGrammarAccess.ExpressionElements getExpressionAccess() {
		return gaMscript.getExpressionAccess();
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}

	//LetExpression:
	//	"let" assignments+=LetExpressionAssignment ("," assignments+=LetExpressionAssignment)* "in" target=Expression;
	public MscriptGrammarAccess.LetExpressionElements getLetExpressionAccess() {
		return gaMscript.getLetExpressionAccess();
	}
	
	public ParserRule getLetExpressionRule() {
		return getLetExpressionAccess().getRule();
	}

	//LetExpressionAssignment:
	//	(variables+=LetExpressionVariableDeclaration | "(" variables+=LetExpressionVariableDeclaration (","
	//	variables+=LetExpressionVariableDeclaration)+ ")") "=" assignedExpression=Expression;
	public MscriptGrammarAccess.LetExpressionAssignmentElements getLetExpressionAssignmentAccess() {
		return gaMscript.getLetExpressionAssignmentAccess();
	}
	
	public ParserRule getLetExpressionAssignmentRule() {
		return getLetExpressionAssignmentAccess().getRule();
	}

	//LetExpressionVariableDeclaration:
	//	name=ValidID;
	public MscriptGrammarAccess.LetExpressionVariableDeclarationElements getLetExpressionVariableDeclarationAccess() {
		return gaMscript.getLetExpressionVariableDeclarationAccess();
	}
	
	public ParserRule getLetExpressionVariableDeclarationRule() {
		return getLetExpressionVariableDeclarationAccess().getRule();
	}

	//IfExpression:
	//	static?="static"? "if" condition=Expression "then" thenExpression=Expression "else" elseExpression=Expression;
	public MscriptGrammarAccess.IfExpressionElements getIfExpressionAccess() {
		return gaMscript.getIfExpressionAccess();
	}
	
	public ParserRule getIfExpressionRule() {
		return getIfExpressionAccess().getRule();
	}

	//SwitchExpression:
	//	static?="static"? "switch" controlExpression=Expression cases+=SwitchCase* "default" ":" defaultExpression=Expression;
	public MscriptGrammarAccess.SwitchExpressionElements getSwitchExpressionAccess() {
		return gaMscript.getSwitchExpressionAccess();
	}
	
	public ParserRule getSwitchExpressionRule() {
		return getSwitchExpressionAccess().getRule();
	}

	//SwitchCase:
	//	"case" caseExpression=ImpliesExpression ":" resultExpression=Expression;
	public MscriptGrammarAccess.SwitchCaseElements getSwitchCaseAccess() {
		return gaMscript.getSwitchCaseAccess();
	}
	
	public ParserRule getSwitchCaseRule() {
		return getSwitchCaseAccess().getRule();
	}

	//RangeExpression returns Expression:
	//	ImpliesExpression ({RangeExpression.operands+=current} ":" operands+=ImpliesExpression (":"
	//	operands+=ImpliesExpression)?)?;
	public MscriptGrammarAccess.RangeExpressionElements getRangeExpressionAccess() {
		return gaMscript.getRangeExpressionAccess();
	}
	
	public ParserRule getRangeExpressionRule() {
		return getRangeExpressionAccess().getRule();
	}

	//ImpliesExpression returns Expression:
	//	LogicalOrExpression ({ImpliesExpression.leftOperand=current} "=>" rightOperand=LogicalOrExpression)?;
	public MscriptGrammarAccess.ImpliesExpressionElements getImpliesExpressionAccess() {
		return gaMscript.getImpliesExpressionAccess();
	}
	
	public ParserRule getImpliesExpressionRule() {
		return getImpliesExpressionAccess().getRule();
	}

	//LogicalOrExpression returns Expression:
	//	LogicalAndExpression ({LogicalOrExpression.leftOperand=current} "||" rightOperand=LogicalAndExpression)*;
	public MscriptGrammarAccess.LogicalOrExpressionElements getLogicalOrExpressionAccess() {
		return gaMscript.getLogicalOrExpressionAccess();
	}
	
	public ParserRule getLogicalOrExpressionRule() {
		return getLogicalOrExpressionAccess().getRule();
	}

	//LogicalAndExpression returns Expression:
	//	EqualityExpression ({LogicalAndExpression.leftOperand=current} "&&" rightOperand=EqualityExpression)*;
	public MscriptGrammarAccess.LogicalAndExpressionElements getLogicalAndExpressionAccess() {
		return gaMscript.getLogicalAndExpressionAccess();
	}
	
	public ParserRule getLogicalAndExpressionRule() {
		return getLogicalAndExpressionAccess().getRule();
	}

	//EqualityExpression returns Expression:
	//	RelationalExpression ({EqualityExpression.leftOperand=current} operator=EqualityOperator
	//	rightOperand=RelationalExpression)*;
	public MscriptGrammarAccess.EqualityExpressionElements getEqualityExpressionAccess() {
		return gaMscript.getEqualityExpressionAccess();
	}
	
	public ParserRule getEqualityExpressionRule() {
		return getEqualityExpressionAccess().getRule();
	}

	//enum EqualityOperator:
	//	EqualTo="==" | NotEqualTo="!=";
	public MscriptGrammarAccess.EqualityOperatorElements getEqualityOperatorAccess() {
		return gaMscript.getEqualityOperatorAccess();
	}
	
	public EnumRule getEqualityOperatorRule() {
		return getEqualityOperatorAccess().getRule();
	}

	//RelationalExpression returns Expression:
	//	AdditiveExpression => ({RelationalExpression.leftOperand=current} operator=RelationalOperator
	//	rightOperand=AdditiveExpression | {TypeTestExpression.expression=current} "is" typeSpecifier=DataTypeSpecifier)?;
	public MscriptGrammarAccess.RelationalExpressionElements getRelationalExpressionAccess() {
		return gaMscript.getRelationalExpressionAccess();
	}
	
	public ParserRule getRelationalExpressionRule() {
		return getRelationalExpressionAccess().getRule();
	}

	//enum RelationalOperator:
	//	LessThan="<" | LessThanOrEqualTo="<=" | GreaterThan=">" | GreaterThanOrEqualTo=">=";
	public MscriptGrammarAccess.RelationalOperatorElements getRelationalOperatorAccess() {
		return gaMscript.getRelationalOperatorAccess();
	}
	
	public EnumRule getRelationalOperatorRule() {
		return getRelationalOperatorAccess().getRule();
	}

	//AdditiveExpression returns Expression:
	//	MultiplicativeExpression ({AdditiveExpression.leftOperand=current} operator=AdditiveOperator
	//	rightOperand=MultiplicativeExpression)*;
	public MscriptGrammarAccess.AdditiveExpressionElements getAdditiveExpressionAccess() {
		return gaMscript.getAdditiveExpressionAccess();
	}
	
	public ParserRule getAdditiveExpressionRule() {
		return getAdditiveExpressionAccess().getRule();
	}

	//enum AdditiveOperator:
	//	Add="+" | Subtract="-";
	public MscriptGrammarAccess.AdditiveOperatorElements getAdditiveOperatorAccess() {
		return gaMscript.getAdditiveOperatorAccess();
	}
	
	public EnumRule getAdditiveOperatorRule() {
		return getAdditiveOperatorAccess().getRule();
	}

	//MultiplicativeExpression returns Expression:
	//	PowerExpression ({MultiplicativeExpression.leftOperand=current} operator=MultiplicativeOperator
	//	rightOperand=PowerExpression)*;
	public MscriptGrammarAccess.MultiplicativeExpressionElements getMultiplicativeExpressionAccess() {
		return gaMscript.getMultiplicativeExpressionAccess();
	}
	
	public ParserRule getMultiplicativeExpressionRule() {
		return getMultiplicativeExpressionAccess().getRule();
	}

	//enum MultiplicativeOperator:
	//	Multiply="*" | Divide="/" | ElementWiseMultiply=".*" | ElementWiseDivide="./";
	public MscriptGrammarAccess.MultiplicativeOperatorElements getMultiplicativeOperatorAccess() {
		return gaMscript.getMultiplicativeOperatorAccess();
	}
	
	public EnumRule getMultiplicativeOperatorRule() {
		return getMultiplicativeOperatorAccess().getRule();
	}

	//PowerExpression returns Expression:
	//	UnaryExpression ({PowerExpression.operand=current} operator=PowerOperator exponent=UnaryExpression)?;
	public MscriptGrammarAccess.PowerExpressionElements getPowerExpressionAccess() {
		return gaMscript.getPowerExpressionAccess();
	}
	
	public ParserRule getPowerExpressionRule() {
		return getPowerExpressionAccess().getRule();
	}

	//enum PowerOperator:
	//	Power="^" | ElementWisePower=".^";
	public MscriptGrammarAccess.PowerOperatorElements getPowerOperatorAccess() {
		return gaMscript.getPowerOperatorAccess();
	}
	
	public EnumRule getPowerOperatorRule() {
		return getPowerOperatorAccess().getRule();
	}

	//UnaryExpression returns Expression:
	//	PostfixExpression | {UnaryExpression} operator=UnaryOperator operand=PostfixExpression;
	public MscriptGrammarAccess.UnaryExpressionElements getUnaryExpressionAccess() {
		return gaMscript.getUnaryExpressionAccess();
	}
	
	public ParserRule getUnaryExpressionRule() {
		return getUnaryExpressionAccess().getRule();
	}

	//enum UnaryOperator:
	//	Negate="-" | LogicalNot="!";
	public MscriptGrammarAccess.UnaryOperatorElements getUnaryOperatorAccess() {
		return gaMscript.getUnaryOperatorAccess();
	}
	
	public EnumRule getUnaryOperatorRule() {
		return getUnaryOperatorAccess().getRule();
	}

	//PostfixExpression returns Expression:
	//	ArrayElementAccess ({PostfixExpression.operand=current} operator=PostfixOperator)?;
	public MscriptGrammarAccess.PostfixExpressionElements getPostfixExpressionAccess() {
		return gaMscript.getPostfixExpressionAccess();
	}
	
	public ParserRule getPostfixExpressionRule() {
		return getPostfixExpressionAccess().getRule();
	}

	//enum PostfixOperator:
	//	Derivative="\'";
	public MscriptGrammarAccess.PostfixOperatorElements getPostfixOperatorAccess() {
		return gaMscript.getPostfixOperatorAccess();
	}
	
	public EnumRule getPostfixOperatorRule() {
		return getPostfixOperatorAccess().getRule();
	}

	//ArrayElementAccess returns Expression:
	//	MemberFeatureCall ({ArrayElementAccess.array=current} "[" subscripts+=ArraySubscript ("," subscripts+=ArraySubscript)*
	//	"]")*;
	public MscriptGrammarAccess.ArrayElementAccessElements getArrayElementAccessAccess() {
		return gaMscript.getArrayElementAccessAccess();
	}
	
	public ParserRule getArrayElementAccessRule() {
		return getArrayElementAccessAccess().getRule();
	}

	//MemberFeatureCall returns Expression:
	//	PrimaryExpression ({MemberVariableAccess.target=current} "." memberVariable=[CallableElement|ValidID] |
	//	{FunctionCall.arguments+=current} "." feature=[CallableElement|ValidID] "(" (arguments+=Expression (","
	//	arguments+=Expression)*)? ")" | {IterationCall.target=current} "." identifier=ValidID "("
	//	iterationVariables+=IterationVariableDeclaration ("," iterationVariables+=IterationVariableDeclaration)* (";"
	//	accumulator=IterationAccumulator)? (";" breakCondition=Expression)? "|" expression=Expression ")")*;
	public MscriptGrammarAccess.MemberFeatureCallElements getMemberFeatureCallAccess() {
		return gaMscript.getMemberFeatureCallAccess();
	}
	
	public ParserRule getMemberFeatureCallRule() {
		return getMemberFeatureCallAccess().getRule();
	}

	//AssignableMemberFeatureCall returns Expression:
	//	AssignablePrimaryExpression ({MemberVariableAccess.target=current} "." memberVariable=[CallableElement|ValidID])*;
	public MscriptGrammarAccess.AssignableMemberFeatureCallElements getAssignableMemberFeatureCallAccess() {
		return gaMscript.getAssignableMemberFeatureCallAccess();
	}
	
	public ParserRule getAssignableMemberFeatureCallRule() {
		return getAssignableMemberFeatureCallAccess().getRule();
	}

	//IterationAccumulator:
	//	name=ValidID "=" initializer=Expression;
	public MscriptGrammarAccess.IterationAccumulatorElements getIterationAccumulatorAccess() {
		return gaMscript.getIterationAccumulatorAccess();
	}
	
	public ParserRule getIterationAccumulatorRule() {
		return getIterationAccumulatorAccess().getRule();
	}

	//IterationVariableDeclaration:
	//	name=ValidID;
	public MscriptGrammarAccess.IterationVariableDeclarationElements getIterationVariableDeclarationAccess() {
		return gaMscript.getIterationVariableDeclarationAccess();
	}
	
	public ParserRule getIterationVariableDeclarationRule() {
		return getIterationVariableDeclarationAccess().getRule();
	}

	//ArraySubscript:
	//	slice?=":" | expression=Expression;
	public MscriptGrammarAccess.ArraySubscriptElements getArraySubscriptAccess() {
		return gaMscript.getArraySubscriptAccess();
	}
	
	public ParserRule getArraySubscriptRule() {
		return getArraySubscriptAccess().getRule();
	}

	//PrimaryExpression returns Expression:
	//	Literal | FeatureCall | UnitConstructionOperator | ArrayConstructionOperator | ArrayConcatenationOperator |
	//	ParenthesizedExpression | EndExpression | AlgorithmExpression;
	public MscriptGrammarAccess.PrimaryExpressionElements getPrimaryExpressionAccess() {
		return gaMscript.getPrimaryExpressionAccess();
	}
	
	public ParserRule getPrimaryExpressionRule() {
		return getPrimaryExpressionAccess().getRule();
	}

	//AssignablePrimaryExpression returns Expression:
	//	FeatureCall | ParenthesizedExpression;
	public MscriptGrammarAccess.AssignablePrimaryExpressionElements getAssignablePrimaryExpressionAccess() {
		return gaMscript.getAssignablePrimaryExpressionAccess();
	}
	
	public ParserRule getAssignablePrimaryExpressionRule() {
		return getAssignablePrimaryExpressionAccess().getRule();
	}

	//Literal:
	//	NumericLiteral | BooleanLiteral | StringLiteral;
	public MscriptGrammarAccess.LiteralElements getLiteralAccess() {
		return gaMscript.getLiteralAccess();
	}
	
	public ParserRule getLiteralRule() {
		return getLiteralAccess().getRule();
	}

	//NumericLiteral:
	//	IntegerLiteral | RealLiteral;
	public MscriptGrammarAccess.NumericLiteralElements getNumericLiteralAccess() {
		return gaMscript.getNumericLiteralAccess();
	}
	
	public ParserRule getNumericLiteralRule() {
		return getNumericLiteralAccess().getRule();
	}

	//RealLiteral:
	//	data=RealData unit=Unit;
	public MscriptGrammarAccess.RealLiteralElements getRealLiteralAccess() {
		return gaMscript.getRealLiteralAccess();
	}
	
	public ParserRule getRealLiteralRule() {
		return getRealLiteralAccess().getRule();
	}

	//RealData hidden():
	//	ValidInt ("." ValidInt (IJ | EXPIJ | E ("+" | "-") ValidInt IJ?)? | (EXPIJ | E ("+" | "-") ValidInt IJ?));
	public MscriptGrammarAccess.RealDataElements getRealDataAccess() {
		return gaMscript.getRealDataAccess();
	}
	
	public ParserRule getRealDataRule() {
		return getRealDataAccess().getRule();
	}

	//IntegerLiteral:
	//	data=IntegerData unit=Unit;
	public MscriptGrammarAccess.IntegerLiteralElements getIntegerLiteralAccess() {
		return gaMscript.getIntegerLiteralAccess();
	}
	
	public ParserRule getIntegerLiteralRule() {
		return getIntegerLiteralAccess().getRule();
	}

	//IntegerData hidden():
	//	ValidInt IJ?;
	public MscriptGrammarAccess.IntegerDataElements getIntegerDataAccess() {
		return gaMscript.getIntegerDataAccess();
	}
	
	public ParserRule getIntegerDataRule() {
		return getIntegerDataAccess().getRule();
	}

	//BooleanLiteral:
	//	{BooleanLiteral} (true?="true" | "false");
	public MscriptGrammarAccess.BooleanLiteralElements getBooleanLiteralAccess() {
		return gaMscript.getBooleanLiteralAccess();
	}
	
	public ParserRule getBooleanLiteralRule() {
		return getBooleanLiteralAccess().getRule();
	}

	//StringLiteral:
	//	value=STRING;
	public MscriptGrammarAccess.StringLiteralElements getStringLiteralAccess() {
		return gaMscript.getStringLiteralAccess();
	}
	
	public ParserRule getStringLiteralRule() {
		return getStringLiteralAccess().getRule();
	}

	//FeatureCall returns Expression:
	//	VariableAccess | FunctionCall;
	public MscriptGrammarAccess.FeatureCallElements getFeatureCallAccess() {
		return gaMscript.getFeatureCallAccess();
	}
	
	public ParserRule getFeatureCallRule() {
		return getFeatureCallAccess().getRule();
	}

	//VariableAccess returns Expression:
	//	{VariableAccess} feature=[CallableElement|QualifiedName] ("{" stepExpression=StepExpression "}")?;
	public MscriptGrammarAccess.VariableAccessElements getVariableAccessAccess() {
		return gaMscript.getVariableAccessAccess();
	}
	
	public ParserRule getVariableAccessRule() {
		return getVariableAccessAccess().getRule();
	}

	//FunctionCall returns Expression:
	//	{FunctionCall} feature=[CallableElement|QualifiedName] "(" (arguments+=Expression ("," arguments+=Expression)*)? ")";
	public MscriptGrammarAccess.FunctionCallElements getFunctionCallAccess() {
		return gaMscript.getFunctionCallAccess();
	}
	
	public ParserRule getFunctionCallRule() {
		return getFunctionCallAccess().getRule();
	}

	//StepExpression:
	//	RangeStepExpression;
	public MscriptGrammarAccess.StepExpressionElements getStepExpressionAccess() {
		return gaMscript.getStepExpressionAccess();
	}
	
	public ParserRule getStepExpressionRule() {
		return getStepExpressionAccess().getRule();
	}

	//RangeStepExpression returns StepExpression:
	//	AdditiveStepExpression ({RangeStepExpression.start=current} ".." end=AdditiveStepExpression)?;
	public MscriptGrammarAccess.RangeStepExpressionElements getRangeStepExpressionAccess() {
		return gaMscript.getRangeStepExpressionAccess();
	}
	
	public ParserRule getRangeStepExpressionRule() {
		return getRangeStepExpressionAccess().getRule();
	}

	//AdditiveStepExpression returns StepExpression:
	//	NegateStepExpression ({AdditiveStepExpression.leftOperand=current} operator=AdditiveOperator
	//	rightOperand=NegateStepExpression)*;
	public MscriptGrammarAccess.AdditiveStepExpressionElements getAdditiveStepExpressionAccess() {
		return gaMscript.getAdditiveStepExpressionAccess();
	}
	
	public ParserRule getAdditiveStepExpressionRule() {
		return getAdditiveStepExpressionAccess().getRule();
	}

	//NegateStepExpression returns StepExpression:
	//	PrimitiveStepExpression | {NegateStepExpression} "-" operand=PrimitiveStepExpression;
	public MscriptGrammarAccess.NegateStepExpressionElements getNegateStepExpressionAccess() {
		return gaMscript.getNegateStepExpressionAccess();
	}
	
	public ParserRule getNegateStepExpressionRule() {
		return getNegateStepExpressionAccess().getRule();
	}

	//PrimitiveStepExpression returns StepExpression:
	//	StepLiteral | StepN;
	public MscriptGrammarAccess.PrimitiveStepExpressionElements getPrimitiveStepExpressionAccess() {
		return gaMscript.getPrimitiveStepExpressionAccess();
	}
	
	public ParserRule getPrimitiveStepExpressionRule() {
		return getPrimitiveStepExpressionAccess().getRule();
	}

	//StepLiteral:
	//	value=ValidInt;
	public MscriptGrammarAccess.StepLiteralElements getStepLiteralAccess() {
		return gaMscript.getStepLiteralAccess();
	}
	
	public ParserRule getStepLiteralRule() {
		return getStepLiteralAccess().getRule();
	}

	//StepN:
	//	{StepN} N;
	public MscriptGrammarAccess.StepNElements getStepNAccess() {
		return gaMscript.getStepNAccess();
	}
	
	public ParserRule getStepNRule() {
		return getStepNAccess().getRule();
	}

	//ArrayConstructionOperator:
	//	"{" expressions+=Expression (("," expressions+=Expression)* | "for" iterationClauses+=ArrayConstructionIterationClause
	//	("," iterationClauses+=ArrayConstructionIterationClause)*) "}";
	public MscriptGrammarAccess.ArrayConstructionOperatorElements getArrayConstructionOperatorAccess() {
		return gaMscript.getArrayConstructionOperatorAccess();
	}
	
	public ParserRule getArrayConstructionOperatorRule() {
		return getArrayConstructionOperatorAccess().getRule();
	}

	//ArrayConstructionIterationClause:
	//	variableName=ValidID "in" collectionExpression=Expression;
	public MscriptGrammarAccess.ArrayConstructionIterationClauseElements getArrayConstructionIterationClauseAccess() {
		return gaMscript.getArrayConstructionIterationClauseAccess();
	}
	
	public ParserRule getArrayConstructionIterationClauseRule() {
		return getArrayConstructionIterationClauseAccess().getRule();
	}

	//ArrayConcatenationOperator:
	//	"[" rows+=ExpressionList (";" rows+=ExpressionList)* "]";
	public MscriptGrammarAccess.ArrayConcatenationOperatorElements getArrayConcatenationOperatorAccess() {
		return gaMscript.getArrayConcatenationOperatorAccess();
	}
	
	public ParserRule getArrayConcatenationOperatorRule() {
		return getArrayConcatenationOperatorAccess().getRule();
	}

	//ExpressionList:
	//	expressions+=Expression ("," expressions+=Expression)*;
	public MscriptGrammarAccess.ExpressionListElements getExpressionListAccess() {
		return gaMscript.getExpressionListAccess();
	}
	
	public ParserRule getExpressionListRule() {
		return getExpressionListAccess().getRule();
	}

	//UnitConstructionOperator:
	//	"$" unit=ExplicitUnit;
	public MscriptGrammarAccess.UnitConstructionOperatorElements getUnitConstructionOperatorAccess() {
		return gaMscript.getUnitConstructionOperatorAccess();
	}
	
	public ParserRule getUnitConstructionOperatorRule() {
		return getUnitConstructionOperatorAccess().getRule();
	}

	//ParenthesizedExpression:
	//	"(" expressions+=Expression ("," expressions+=Expression)* ")";
	public MscriptGrammarAccess.ParenthesizedExpressionElements getParenthesizedExpressionAccess() {
		return gaMscript.getParenthesizedExpressionAccess();
	}
	
	public ParserRule getParenthesizedExpressionRule() {
		return getParenthesizedExpressionAccess().getRule();
	}

	//EndExpression:
	//	{EndExpression} "end";
	public MscriptGrammarAccess.EndExpressionElements getEndExpressionAccess() {
		return gaMscript.getEndExpressionAccess();
	}
	
	public ParserRule getEndExpressionRule() {
		return getEndExpressionAccess().getRule();
	}

	//AlgorithmExpression returns Expression:
	//	{AlgorithmExpression} "algo" body=Compound;
	public MscriptGrammarAccess.AlgorithmExpressionElements getAlgorithmExpressionAccess() {
		return gaMscript.getAlgorithmExpressionAccess();
	}
	
	public ParserRule getAlgorithmExpressionRule() {
		return getAlgorithmExpressionAccess().getRule();
	}

	//Compound:
	//	{Compound} "{" statements+=Statement* "}";
	public MscriptGrammarAccess.CompoundElements getCompoundAccess() {
		return gaMscript.getCompoundAccess();
	}
	
	public ParserRule getCompoundRule() {
		return getCompoundAccess().getRule();
	}

	//Statement:
	//	Compound | Assignment | LocalVariableDeclaration | IfStatement | WhileStatement | DoWhileStatement | ForStatement |
	//	ContinueStatement | BreakStatement | ReturnStatement;
	public MscriptGrammarAccess.StatementElements getStatementAccess() {
		return gaMscript.getStatementAccess();
	}
	
	public ParserRule getStatementRule() {
		return getStatementAccess().getRule();
	}

	//Assignment:
	//	target=AssignableMemberFeatureCall "=" assignedExpression=Expression ";";
	public MscriptGrammarAccess.AssignmentElements getAssignmentAccess() {
		return gaMscript.getAssignmentAccess();
	}
	
	public ParserRule getAssignmentRule() {
		return getAssignmentAccess().getRule();
	}

	//LocalVariableDeclaration:
	//	"var" name=ValidID "=" initializer=Expression ";";
	public MscriptGrammarAccess.LocalVariableDeclarationElements getLocalVariableDeclarationAccess() {
		return gaMscript.getLocalVariableDeclarationAccess();
	}
	
	public ParserRule getLocalVariableDeclarationRule() {
		return getLocalVariableDeclarationAccess().getRule();
	}

	//IfStatement:
	//	"if" "(" condition=Expression ")" thenStatement=Statement ("else" elseStatement=Statement)?;
	public MscriptGrammarAccess.IfStatementElements getIfStatementAccess() {
		return gaMscript.getIfStatementAccess();
	}
	
	public ParserRule getIfStatementRule() {
		return getIfStatementAccess().getRule();
	}

	//WhileStatement:
	//	"while" "(" condition=Expression ")" body=Statement;
	public MscriptGrammarAccess.WhileStatementElements getWhileStatementAccess() {
		return gaMscript.getWhileStatementAccess();
	}
	
	public ParserRule getWhileStatementRule() {
		return getWhileStatementAccess().getRule();
	}

	//ForStatement:
	//	"for" "(" iterationVariable=IterationVariableDeclaration "in" collectionExpression=Expression ")" body=Statement;
	public MscriptGrammarAccess.ForStatementElements getForStatementAccess() {
		return gaMscript.getForStatementAccess();
	}
	
	public ParserRule getForStatementRule() {
		return getForStatementAccess().getRule();
	}

	//DoWhileStatement:
	//	"do" body=Statement "while" "(" condition=Expression ")" ";";
	public MscriptGrammarAccess.DoWhileStatementElements getDoWhileStatementAccess() {
		return gaMscript.getDoWhileStatementAccess();
	}
	
	public ParserRule getDoWhileStatementRule() {
		return getDoWhileStatementAccess().getRule();
	}

	//ContinueStatement:
	//	{ContinueStatement} "continue" ";";
	public MscriptGrammarAccess.ContinueStatementElements getContinueStatementAccess() {
		return gaMscript.getContinueStatementAccess();
	}
	
	public ParserRule getContinueStatementRule() {
		return getContinueStatementAccess().getRule();
	}

	//BreakStatement:
	//	{BreakStatement} "break" ";";
	public MscriptGrammarAccess.BreakStatementElements getBreakStatementAccess() {
		return gaMscript.getBreakStatementAccess();
	}
	
	public ParserRule getBreakStatementRule() {
		return getBreakStatementAccess().getRule();
	}

	//ReturnStatement:
	//	"return" expression=Expression ";";
	public MscriptGrammarAccess.ReturnStatementElements getReturnStatementAccess() {
		return gaMscript.getReturnStatementAccess();
	}
	
	public ParserRule getReturnStatementRule() {
		return getReturnStatementAccess().getRule();
	}

	/// *
	// * Unit expressions
	// * / Unit:
	//	{Unit} ("(" ")" | "(" numerator=UnitNumerator ("/" denominator=UnitDenominator)? ")" |
	//	numerator=ImplicitUnitNumerator);
	public MscriptGrammarAccess.UnitElements getUnitAccess() {
		return gaMscript.getUnitAccess();
	}
	
	public ParserRule getUnitRule() {
		return getUnitAccess().getRule();
	}

	//ExplicitUnit returns Unit:
	//	"(" numerator=UnitNumerator ("/" denominator=UnitDenominator)? ")";
	public MscriptGrammarAccess.ExplicitUnitElements getExplicitUnitAccess() {
		return gaMscript.getExplicitUnitAccess();
	}
	
	public ParserRule getExplicitUnitRule() {
		return getExplicitUnitAccess().getRule();
	}

	//UnitNumerator:
	//	{UnitNumerator} ONE | factors+=UnitFactor ("*" factors+=UnitFactor)*;
	public MscriptGrammarAccess.UnitNumeratorElements getUnitNumeratorAccess() {
		return gaMscript.getUnitNumeratorAccess();
	}
	
	public ParserRule getUnitNumeratorRule() {
		return getUnitNumeratorAccess().getRule();
	}

	//ImplicitUnitNumerator returns UnitNumerator:
	//	{UnitNumerator};
	public MscriptGrammarAccess.ImplicitUnitNumeratorElements getImplicitUnitNumeratorAccess() {
		return gaMscript.getImplicitUnitNumeratorAccess();
	}
	
	public ParserRule getImplicitUnitNumeratorRule() {
		return getImplicitUnitNumeratorAccess().getRule();
	}

	//UnitDenominator:
	//	factors+=UnitFactor | "(" factors+=UnitFactor ("*" factors+=UnitFactor)* ")";
	public MscriptGrammarAccess.UnitDenominatorElements getUnitDenominatorAccess() {
		return gaMscript.getUnitDenominatorAccess();
	}
	
	public ParserRule getUnitDenominatorRule() {
		return getUnitDenominatorAccess().getRule();
	}

	//UnitFactor:
	//	symbol=ValidID ("^" exponent=UnitExponent)?;
	public MscriptGrammarAccess.UnitFactorElements getUnitFactorAccess() {
		return gaMscript.getUnitFactorAccess();
	}
	
	public ParserRule getUnitFactorRule() {
		return getUnitFactorAccess().getRule();
	}

	//UnitExponent returns ecore::EInt:
	//	"-"? ValidInt;
	public MscriptGrammarAccess.UnitExponentElements getUnitExponentAccess() {
		return gaMscript.getUnitExponentAccess();
	}
	
	public ParserRule getUnitExponentRule() {
		return getUnitExponentAccess().getRule();
	}

	//QualifiedName:
	//	ValidID ("::" ValidID)*;
	public MscriptGrammarAccess.QualifiedNameElements getQualifiedNameAccess() {
		return gaMscript.getQualifiedNameAccess();
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}

	//ValidInt returns ecore::EInt:
	//	ONE | INT;
	public MscriptGrammarAccess.ValidIntElements getValidIntAccess() {
		return gaMscript.getValidIntAccess();
	}
	
	public ParserRule getValidIntRule() {
		return getValidIntAccess().getRule();
	}

	//ValidID:
	//	N | IJ | E | EXPIJ | ID;
	public MscriptGrammarAccess.ValidIDElements getValidIDAccess() {
		return gaMscript.getValidIDAccess();
	}
	
	public ParserRule getValidIDRule() {
		return getValidIDAccess().getRule();
	}

	/// *
	// * Terminals
	// * / terminal N:
	//	"n";
	public TerminalRule getNRule() {
		return gaMscript.getNRule();
	} 

	//terminal IJ:
	//	"i" | "j";
	public TerminalRule getIJRule() {
		return gaMscript.getIJRule();
	} 

	//terminal E:
	//	"e" | "E";
	public TerminalRule getERule() {
		return gaMscript.getERule();
	} 

	//terminal EXPIJ:
	//	E "0".."9"+ IJ?;
	public TerminalRule getEXPIJRule() {
		return gaMscript.getEXPIJRule();
	} 

	//terminal ONE:
	//	"1";
	public TerminalRule getONERule() {
		return gaMscript.getONERule();
	} 

	//terminal INT:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaMscript.getINTRule();
	} 

	//terminal ID:
	//	"_"? ("a".."z" | "A".."Z") ("0".."9" | "_" | "a".."z" | "A".."Z")*;
	public TerminalRule getIDRule() {
		return gaMscript.getIDRule();
	} 

	//terminal STRING:
	//	"\"" (!("\\" | "\"") | "\\" ("\'" | "\"" | "?" | "\\" | "a" | "b" | "f" | "n" | "r" | "t" | "v"))* "\"";
	public TerminalRule getSTRINGRule() {
		return gaMscript.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaMscript.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaMscript.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaMscript.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaMscript.getANY_OTHERRule();
	} 
}
