/*
* generated by Xtext
*/
package org.eclipselabs.damos.simulation.simulationmodel.ui.contentassist;

import org.eclipselabs.damos.simulation.simulationmodel.ui.contentassist.AbstractSimulationModelProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SimulationModelProposalProvider extends AbstractSimulationModelProposalProvider {

}
