<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dscript" nsURI="http://www.eclipselabs.org/damos/2011/Dscript"
    nsPrefix="dscript">
  <eClassifiers xsi:type="ecore:EClass" name="Root" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="blockTypes" upperBound="-1"
        eType="ecore:EClass ../../org.eclipselabs.damos.dml/model/DML.ecore#//BlockType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemInterfaces" upperBound="-1"
        eType="ecore:EClass ../../org.eclipselabs.damos.dml/model/DML.ecore#//SystemInterface"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DscriptBlockType" eSuperTypes="../../org.eclipselabs.damos.dml/model/DML.ecore#//BlockType ../../org.eclipselabs.damos.mscript/model/Mscript.ecore#//TopLevelContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="importDeclarations" upperBound="-1"
        eType="ecore:EClass ../../org.eclipselabs.damos.mscript/model/Mscript.ecore#//ImportDeclaration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behavior" eType="#//BehaviorDeclaration"
        containment="true" eOpposite="#//BehaviorDeclaration/blockType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DscriptInputDefinition" eSuperTypes="../../org.eclipselabs.damos.dml/model/DML.ecore#//InputDefinition ../../org.eclipselabs.damos.mscript/model/Mscript.ecore#//InputParameterDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="DscriptOutputDefinition" eSuperTypes="../../org.eclipselabs.damos.dml/model/DML.ecore#//OutputDefinition ../../org.eclipselabs.damos.mscript/model/Mscript.ecore#//OutputParameterDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="DscriptParameter" eSuperTypes="../../org.eclipselabs.damos.dml/model/DML.ecore#//Parameter ../../org.eclipselabs.damos.mscript/model/Mscript.ecore#//InputParameterDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="BehaviorDeclaration" eSuperTypes="../../org.eclipselabs.damos.mscript/model/Mscript.ecore#//FunctionDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="blockType" eType="#//DscriptBlockType"
        eOpposite="#//DscriptBlockType/behavior"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allImplicitInputParameterDeclarations"
        upperBound="-1" eType="#//ImplicitInputParameterDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allImplicitOutputParameterDeclarations"
        upperBound="-1" eType="#//ImplicitOutputParameterDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImplicitInputParameterDeclaration" abstract="true"
      eSuperTypes="../../org.eclipselabs.damos.mscript/model/Mscript.ecore#//InputParameterDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="ImplicitOutputParameterDeclaration"
      abstract="true" eSuperTypes="../../org.eclipselabs.damos.mscript/model/Mscript.ecore#//OutputParameterDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="InputMessageParameterDeclaration" eSuperTypes="#//ImplicitInputParameterDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutputMessageParameterDeclaration" eSuperTypes="#//ImplicitOutputParameterDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="DscriptSystemInterface" eSuperTypes="../../org.eclipselabs.damos.dml/model/DML.ecore#//SystemInterface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="importDeclarations" upperBound="-1"
        eType="ecore:EClass ../../org.eclipselabs.damos.mscript/model/Mscript.ecore#//ImportDeclaration"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DscriptDataTypeSpecification" eSuperTypes="../../org.eclipselabs.damos.dml/model/DML.ecore#//DataTypeSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeSpecifier" eType="ecore:EClass ../../org.eclipselabs.damos.mscript/model/Mscript.ecore#//TypeSpecifier"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass ../../org.eclipselabs.damos.mscript/model/Mscript.ecore#//Type"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DscriptValueSpecification" eSuperTypes="../../org.eclipselabs.damos.dml/model/DML.ecore#//ValueSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass ../../org.eclipselabs.damos.mscript/model/Mscript.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
