/*
* generated by Xtext
*/
package org.eclipselabs.damos.dconfig.ui.contentassist;

import org.eclipselabs.damos.dconfig.ui.contentassist.AbstractDconfigProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class DconfigProposalProvider extends AbstractDconfigProposalProvider {

}
