/*
 * generated by Xtext
 */
package com.yakindu.statechart.formatting;

import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;

/**
 * This class contains custom formatting description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#formatting
 * on how and when to use it 
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an example
 */
public class WorkflowFormatter extends AbstractDeclarativeFormatter {
	
	@Override
	protected void configureFormatting(FormattingConfig c) {
		com.yakindu.statechart.services.WorkflowGrammarAccess f = (com.yakindu.statechart.services.WorkflowGrammarAccess) getGrammarAccess();

		//...
	}
}
