<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dmltext"
    nsURI="http://www.eclipselabs.org/damos/DMLText/1.0.0" nsPrefix="dmltext">
  <eClassifiers xsi:type="ecore:EClass" name="Root" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="blockTypes" upperBound="-1"
        eType="ecore:EClass ../../org.eclipselabs.damos.dml/model/DML.ecore#//BlockType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemInterfaces" upperBound="-1"
        eType="ecore:EClass ../../org.eclipselabs.damos.dml/model/DML.ecore#//SystemInterface"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MscriptDataTypeSpecification" eSuperTypes="../../org.eclipselabs.damos.dml/model/DML.ecore#//DataTypeSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="specifier" eType="ecore:EClass ../../org.eclipselabs.mscript.language/model/Mscript.ecore#//DataTypeSpecifier"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass ../../org.eclipselabs.mscript.typesystem/model/TypeSystem.ecore#//DataType"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MscriptBehaviorSpecification" eSuperTypes="../../org.eclipselabs.damos.dml/model/DML.ecore#//BehaviorSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" eType="ecore:EClass ../../org.eclipselabs.mscript.language/model/Mscript.ecore#//Module"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MscriptValueSpecification" eSuperTypes="../../org.eclipselabs.damos.dml/model/DML.ecore#//ValueSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass ../../org.eclipselabs.mscript.typesystem/model/TypeSystem.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
