<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dmltext" nsURI="http://www.eclipselabs.org/damos/2011/DMLText"
    nsPrefix="dmltext">
  <eClassifiers xsi:type="ecore:EClass" name="Root" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="blockTypes" upperBound="-1"
        eType="ecore:EClass ../../org.eclipselabs.damos.dml/model/DML.ecore#//BlockType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemInterfaces" upperBound="-1"
        eType="ecore:EClass ../../org.eclipselabs.damos.dml/model/DML.ecore#//SystemInterface"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MscriptBlockType" eSuperTypes="../../org.eclipselabs.damos.dml/model/DML.ecore#//BlockType ../../org.eclipselabs.damos.mscript/model/Mscript.ecore#//TopLevelContainer ../../org.eclipselabs.damos.mscript/model/Mscript.ecore#//PackageFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="importDeclarations" upperBound="-1"
        eType="ecore:EClass ../../org.eclipselabs.damos.mscript/model/Mscript.ecore#//ImportDeclaration"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MscriptSystemInterface" eSuperTypes="../../org.eclipselabs.damos.dml/model/DML.ecore#//SystemInterface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="importDeclarations" upperBound="-1"
        eType="ecore:EClass ../../org.eclipselabs.damos.mscript/model/Mscript.ecore#//ImportDeclaration"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MscriptDataTypeSpecification" eSuperTypes="../../org.eclipselabs.damos.dml/model/DML.ecore#//DataTypeSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeSpecifier" eType="ecore:EClass ../../org.eclipselabs.damos.mscript/model/Mscript.ecore#//TypeSpecifier"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass ../../org.eclipselabs.damos.mscript/model/Mscript.ecore#//Type"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MscriptValueSpecification" eSuperTypes="../../org.eclipselabs.damos.dml/model/DML.ecore#//ValueSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass ../../org.eclipselabs.damos.mscript/model/Mscript.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
