
/*
 * generated by Xtext
 */
 
package com.yakindu.statechart.model.expressions.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class StatechartExpressionsExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return com.yakindu.statechart.model.expressions.ui.internal.StatechartExpressionsActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return com.yakindu.statechart.model.expressions.ui.internal.StatechartExpressionsActivator.getInstance().getInjector("com.yakindu.statechart.model.expressions.StatechartExpressions");
	}
	
}
