/*
* generated by Xtext
*/
package org.eclipselabs.damos.mscript.computationmodel.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ComputationModelAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/eclipselabs/damos/mscript/computationmodel/parser/antlr/internal/InternalComputationModel.tokens");
	}
}
