/*
 * generated by Xtext
 */
package org.eclipselabs.damos.codegen.c.cgenmodel.scoping;

import org.eclipselabs.damos.mscript.scoping.MscriptScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class CGenModelScopeProvider extends MscriptScopeProvider {

}
