/*
 * generated by Xtext
 */
package org.eclipselabs.damos.execution.executionmodel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ExecutionModelUiModule extends org.eclipselabs.damos.execution.executionmodel.ui.AbstractExecutionModelUiModule {
	public ExecutionModelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
