/*
 * generated by Xtext
 */
package org.eclipselabs.damos.dconfig.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DconfigExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.eclipselabs.damos.dconfig.ui.internal.DconfigActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.eclipselabs.damos.dconfig.ui.internal.DconfigActivator.getInstance().getInjector("org.eclipselabs.damos.dconfig.Dconfig");
	}
	
}
