/*
* generated by Xtext
*/
package org.eclipse.damos.dscript.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class DscriptOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
