/*
 * generated by Xtext
 */
package org.eclipselabs.damos.codegen.c.cgenmodel;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.conversion.impl.AbstractIDValueConverter;
import org.eclipse.xtext.conversion.impl.QualifiedNameValueConverter;
import org.eclipselabs.damos.mscript.conversion.MscriptIDValueConverter;
import org.eclipselabs.damos.mscript.conversion.MscriptQualifiedNameValueConverter;
import org.eclipselabs.damos.mscript.conversion.MscriptTerminalConverters;
import org.eclipselabs.damos.mscript.naming.MscriptQualifiedNameConverter;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CGenModelRuntimeModule extends org.eclipselabs.damos.codegen.c.cgenmodel.AbstractCGenModelRuntimeModule {

	public Class<? extends AbstractIDValueConverter> bindAbstractIDValueConverter() {
		return MscriptIDValueConverter.class;
	}

	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
		return MscriptTerminalConverters.class;
	}

	public Class<? extends QualifiedNameValueConverter> bindQualifiedNameValueConverter() {
		return MscriptQualifiedNameValueConverter.class;
	}

	public Class<? extends org.eclipse.xtext.naming.IQualifiedNameConverter> bindIQualifiedNameConverter() {
		return MscriptQualifiedNameConverter.class;
	}

}
