<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cgenmodel"
    nsURI="http://www.eclipselabs.org/damos/2011/CGenModel" nsPrefix="cgenmodel">
  <eClassifiers xsi:type="ecore:EClass" name="GenModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executionModel" eType="ecore:EClass ../../org.eclipselabs.damos.execution.executionmodel/model/ExecutionModel.ecore#//ExecutionModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genTopLevelSystem" eType="#//GenTopLevelSystem"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceDirectory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="headerDirectory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mainSourceFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mainHeaderFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="singleton" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenSystem" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="genSubsystems" upperBound="-1"
        eType="#//GenSubsystem" containment="true" eOpposite="#//GenSubsystem/enclosingGenSystem"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenTopLevelSystem" eSuperTypes="#//GenSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fragment" eType="ecore:EClass ../../org.eclipselabs.damos.dml/model/DML.ecore#//Fragment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenSubsystem" eSuperTypes="#//GenSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGenSystem" eType="#//GenSystem"
        eOpposite="#//GenSystem/genSubsystems"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subsystem" eType="ecore:EClass ../../org.eclipselabs.damos.dml/model/DML.ecore#//Subsystem"/>
  </eClassifiers>
</ecore:EPackage>
