/*
 * generated by Xtext
 */
package org.eclipse.damos.dconfig.ui;

import org.eclipse.damos.dconfig.ui.internal.DconfigActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;


/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DconfigExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DconfigActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DconfigActivator.getInstance().getInjector(DconfigActivator.ORG_ECLIPSE_DAMOS_DCONFIG_DCONFIG);
	}
	
}
