/*
* generated by Xtext
*/
package org.eclipselabs.damos.mscript.computationmodel.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class ComputationModelOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
