<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="executiongraph"
    nsURI="http://www.eclipselabs.org/damos/ExecutionGraph/1.0.0" nsPrefix="executiongraph">
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionGraph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialNodes" upperBound="-1"
        eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//Link" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topLevelFragment" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipselabs.damos.dml/model/DML.ecore#//Fragment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataFlows" ordered="false"
        upperBound="-1" eType="#//DataFlow" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node">
    <eOperations name="getIncomingDataFlow" ordered="false" lowerBound="1" eType="#//DataFlowTargetEnd">
      <eParameters name="inputPort" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipselabs.damos.dml/model/DML.ecore#//InputPort"/>
    </eOperations>
    <eOperations name="getOutgoingDataFlow" ordered="false" lowerBound="1" eType="#//DataFlowSourceEnd">
      <eParameters name="outputPort" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipselabs.damos.dml/model/DML.ecore#//OutputPort"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingLinks" upperBound="-1"
        eType="#//Link" eOpposite="#//Link/targetNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingLinks" upperBound="-1"
        eType="#//Link" eOpposite="#//Link/sourceNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipselabs.damos.dml/model/DML.ecore#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingDataFlows" upperBound="-1"
        eType="#//DataFlowSourceEnd" eOpposite="#//DataFlowSourceEnd/node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingDataFlows" upperBound="-1"
        eType="#//DataFlowTargetEnd" eOpposite="#//DataFlowTargetEnd/node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingSubsystems" upperBound="-1"
        eType="ecore:EClass ../../org.eclipselabs.damos.dml/model/DML.ecore#//Subsystem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceNode" ordered="false"
        lowerBound="1" eType="#//Node" eOpposite="#//Node/outgoingLinks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetNode" ordered="false"
        lowerBound="1" eType="#//Node" eOpposite="#//Node/incomingLinks"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataFlowSourceEnd" eSuperTypes="#//DataFlowEnd">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" ordered="false" lowerBound="1"
        eType="ecore:EClass ../../org.eclipselabs.damos.dml/model/DML.ecore#//OutputPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataFlow" ordered="false"
        lowerBound="1" eType="#//DataFlow" eOpposite="#//DataFlow/sourceEnd"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" ordered="false" lowerBound="1"
        eType="#//Node" eOpposite="#//Node/outgoingDataFlows"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataFlowEnd" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataFlow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetEnds" lowerBound="1"
        upperBound="-1" eType="#//DataFlowTargetEnd" containment="true" eOpposite="#//DataFlowTargetEnd/dataFlow"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceEnd" ordered="false"
        lowerBound="1" eType="#//DataFlowSourceEnd" containment="true" eOpposite="#//DataFlowSourceEnd/dataFlow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataFlowTargetEnd" eSuperTypes="#//DataFlowEnd">
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" ordered="false" lowerBound="1"
        eType="#//Node" eOpposite="#//Node/incomingDataFlows"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" ordered="false" lowerBound="1"
        eType="ecore:EClass ../../org.eclipselabs.damos.dml/model/DML.ecore#//InputPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataFlow" ordered="false"
        lowerBound="1" eType="#//DataFlow" eOpposite="#//DataFlow/targetEnds"/>
  </eClassifiers>
</ecore:EPackage>
