/*
 * generated by Xtext
 */
package com.yakindu.statechart.model.expressions;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class StatechartExpressionsRuntimeModule extends com.yakindu.statechart.model.expressions.AbstractStatechartExpressionsRuntimeModule {

}
